import type { GovernanceDocumentMeta } from "@/types/platform/governance";

export interface ExtendedGovernanceMeta extends GovernanceDocumentMeta {
  requiresFounderConfirmation?: boolean;
  requiresPrivacyCounselReview?: boolean;
  requiresEmploymentCounselReview?: boolean;
  requiresEducationCounselReview?: boolean;
  requiresCommercialCounselReview?: boolean;
}

export const GOVERNANCE_MANIFEST: Record<string, ExtendedGovernanceMeta> = {
  // LEGAL HUBS & CONTRACTS
  "legal-hub": {
    id: "gov-legal-hub-001",
    title: "Career OS Legal & Compliance Center",
    slug: "legal-hub",
    category: "LEGAL",
    documentType: "GOVERNANCE_HUB",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Delaware & Federal)",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [],
    sources: [],
    changeSummary: "Established complete multi-tenant legal framework covering individuals, youth, schools, employers, and AI systems.",
  },
  "terms": {
    id: "gov-legal-terms-001",
    title: "General Terms of Service",
    slug: "terms",
    category: "LEGAL",
    documentType: "TERMS_OF_SERVICE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "State of Delaware / United States",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresFounderConfirmation: true,
    requiresCommercialCounselReview: true,
    relatedDocuments: [{ title: "Privacy Policy", href: "/legal/privacy" }, { title: "Acceptable Use Policy", href: "/legal/acceptable-use" }],
    sources: [],
    changeSummary: "Rebuilt terms covering 22 core sections: canonical age model (16+ direct), AI disclaimers, and evidence verification spectrum.",
  },
  "privacy": {
    id: "gov-legal-privacy-001",
    title: "Career OS Privacy Policy",
    slug: "privacy",
    category: "LEGAL",
    documentType: "PRIVACY_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Chief Privacy Officer",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [{ title: "Student Terms of Service", href: "/legal/student-terms" }, { title: "Data Ethics", href: "/trust/data-ethics" }],
    sources: [{ title: "FERPA (20 U.S.C. § 1232g)", citation: "34 CFR Part 99" }, { title: "COPPA", citation: "16 CFR Part 312" }],
    changeSummary: "Comprehensive privacy notice covering 18 sections: data categories, AI LLM provider boundaries, and conditional FERPA school official framework.",
  },
  "cookies": {
    id: "gov-legal-cookies-001",
    title: "Cookie & Browser Storage Policy",
    slug: "cookies",
    category: "LEGAL",
    documentType: "COOKIE_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & Global",
    owner: "Data Privacy Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Privacy Policy", href: "/legal/privacy" }],
    sources: [],
    changeSummary: "Inventory of deployed application storage; zero 3rd-party ad tracking pixels.",
  },
  "acceptable-use": {
    id: "gov-legal-aup-001",
    title: "Acceptable Use Policy",
    slug: "acceptable-use",
    category: "LEGAL",
    documentType: "ACCEPTABLE_USE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global Infrastructure",
    owner: "Trust & Safety Director",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "General Terms of Service", href: "/legal/terms" }],
    sources: [],
    changeSummary: "Explicit prohibitions on credential fabrication, candidate scraping, and discriminatory employer targeting.",
  },
  "ai-terms": {
    id: "gov-legal-ai-terms-001",
    title: "AI System Usage Terms & Disclosure",
    slug: "ai-terms",
    category: "LEGAL",
    documentType: "AI_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & EU Alignment",
    owner: "AI Policy Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "Responsible AI Framework", href: "/trust/responsible-ai" }],
    sources: [{ title: "EU AI Act", citation: "Regulation (EU) 2024/1689" }],
    changeSummary: "Non-human AI disclosure, mentor personas, hallucination disclaimers, and provider model isolation.",
  },
  "student-terms": {
    id: "gov-legal-student-terms-001",
    title: "Student & Youth Terms of Service",
    slug: "student-terms",
    category: "LEGAL",
    documentType: "STUDENT_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Education & Safeguarding Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "Safeguarding Framework", href: "/trust/safeguarding" }],
    sources: [{ title: "FERPA Eligible Student Rule", citation: "34 CFR § 99.5" }],
    changeSummary: "Canonical age model alignment (16+ direct), asset separation, and FERPA transfer rules.",
  },
  "parent-guardian-notice": {
    id: "gov-legal-parent-notice-001",
    title: "Parent & Guardian Privacy Notice",
    slug: "parent-guardian-notice",
    category: "LEGAL",
    documentType: "PARENT_GUARDIAN_NOTICE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Youth Safeguarding Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Student Terms of Service", href: "/legal/student-terms" }],
    sources: [{ title: "COPPA Educational Rule", citation: "16 CFR § 312.5" }],
    changeSummary: "High-trust plain English notice explaining age gating, minor recruiter protections, and FERPA transfer.",
  },
  "school-terms": {
    id: "gov-legal-school-terms-001",
    title: "School & Institutional Terms of Service",
    slug: "school-terms",
    category: "LEGAL",
    documentType: "SCHOOL_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Institutional General Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "Data Processing Addendum", href: "/legal/data-processing" }],
    sources: [{ title: "FERPA School Official Exception", citation: "34 CFR § 99.31(a)(1)(i)(B)" }],
    changeSummary: "Institutional terms covering district authorization, FERPA school official framework, and roster provisioning.",
  },
  "employer-terms": {
    id: "gov-legal-employer-terms-001",
    title: "Employer & Recruiter Terms of Service",
    slug: "employer-terms",
    category: "LEGAL",
    documentType: "EMPLOYER_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Commercial Legal Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "Employer Ethical Code", href: "/standards/employer-code" }],
    sources: [{ title: "EEOC Uniform Guidelines", citation: "29 CFR Part 1607" }],
    changeSummary: "Recruiter terms enforcing verified employer identity, real job posts, EEOC non-discrimination, and minor candidate safeguards.",
  },
  "candidate-privacy": {
    id: "gov-legal-candidate-privacy-001",
    title: "Candidate Privacy Notice",
    slug: "candidate-privacy",
    category: "LEGAL",
    documentType: "CANDIDATE_PRIVACY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Privacy & Employment Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Employer Terms of Service", href: "/legal/employer-terms" }],
    sources: [],
    changeSummary: "Explains candidate profile visibility controls, Candidate Hash IDs, access grants, and FCRA non-agency scope notice.",
  },
  "data-processing": {
    id: "gov-legal-dpa-001",
    title: "Data Processing Addendum (DPA)",
    slug: "data-processing",
    category: "LEGAL",
    documentType: "DPA",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & EU",
    owner: "Privacy Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [{ title: "Approved Subprocessors", href: "/legal/subprocessors" }],
    sources: [],
    changeSummary: "Standardized B2B/institutional DPA framework with controller/processor obligations and security annexes.",
  },
  "dpa": {
    id: "gov-legal-dpa-guide-001",
    title: "Institutional DPA Execution Guide",
    slug: "dpa",
    category: "LEGAL",
    documentType: "DPA_GUIDE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Institutional Compliance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Data Processing Addendum", href: "/legal/data-processing" }],
    sources: [],
    changeSummary: "Guide for district administrators on executing Career OS model DPAs (CA CSPA, NY Exhibit E, IL SDPC).",
  },
  "copyright": {
    id: "gov-legal-copyright-001",
    title: "Copyright & Intellectual Property Policy",
    slug: "copyright",
    category: "LEGAL",
    documentType: "COPYRIGHT_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (17 U.S.C. § 512)",
    owner: "IP Counsel",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "General Terms of Service", href: "/legal/terms" }],
    sources: [{ title: "DMCA", citation: "17 U.S.C. § 512" }],
    changeSummary: "DMCA takedown procedure, counter-notice framework, repeat infringer policy, and AI-generated evidence IP rules.",
  },
  "accessibility": {
    id: "gov-legal-a11y-001",
    title: "Web Accessibility Statement",
    slug: "accessibility",
    category: "LEGAL",
    documentType: "ACCESSIBILITY_STATEMENT",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global Standard (WCAG 2.2 AA)",
    owner: "Accessibility & Frontend Engineering Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Accessibility Trust Standard", href: "/trust/accessibility" }],
    sources: [{ title: "WCAG 2.2 AA", citation: "W3C Recommendation" }],
    changeSummary: "WCAG 2.2 Level AA target commitment, keyboard navigation design, screen reader testing, and remediation process.",
  },
  "subprocessors": {
    id: "gov-legal-subprocessors-001",
    title: "Approved Subprocessor List",
    slug: "subprocessors",
    category: "LEGAL",
    documentType: "SUBPROCESSOR_LIST",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Security Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Data Processing Addendum", href: "/legal/data-processing" }],
    sources: [],
    changeSummary: "Active inventory of verified infrastructure sub-processors (Supabase, Vercel, Google Cloud, OpenAI, Anthropic).",
  },
  "data-retention": {
    id: "gov-legal-retention-001",
    title: "Data Retention Schedule & Principles",
    slug: "data-retention",
    category: "LEGAL",
    documentType: "RETENTION_SCHEDULE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Data Governance Committee",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Privacy Policy", href: "/legal/privacy" }],
    sources: [],
    changeSummary: "Data classification retention rules across accounts, Twin assets, chat logs, school records, and backup purge schedules.",
  },
  "version-history": {
    id: "gov-legal-versions-001",
    title: "Legal Center Version History & Archive",
    slug: "version-history",
    category: "LEGAL",
    documentType: "VERSION_HISTORY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Legal Operations Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "General Terms of Service", href: "/legal/terms" }],
    sources: [],
    changeSummary: "Archive index of active and superseded governance document versions.",
  },

  // PART A — TRUST CENTER
  "trust-hub": {
    id: "gov-trust-hub-001",
    title: "Career OS Trust & Security Hub",
    slug: "trust",
    category: "TRUST",
    documentType: "GOVERNANCE_HUB",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & Global",
    owner: "Head of Trust & Security",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Responsible AI", href: "/trust/responsible-ai" }, { title: "Security Architecture", href: "/trust/security" }],
    sources: [],
    changeSummary: "Directory of Career OS trust principles, control status taxonomy (LIVE, IMPLEMENTED, IN_PROGRESS, PLANNED), and security practices.",
  },
  "responsible-ai": {
    id: "gov-trust-rai-001",
    title: "Responsible AI Framework & System Register",
    slug: "trust/responsible-ai",
    category: "TRUST",
    documentType: "AI_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "AI Ethics Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "AI Transparency", href: "/trust/ai-transparency" }, { title: "Human Oversight", href: "/trust/human-oversight" }],
    sources: [{ title: "NIST AI Risk Management Framework", citation: "NIST AI 100-1" }],
    changeSummary: "14 core responsible AI principles and internal AI System Register architecture.",
  },
  "ai-transparency": {
    id: "gov-trust-ait-001",
    title: "AI Transparency, Decision Factors & Provenance",
    slug: "trust/ai-transparency",
    category: "TRUST",
    documentType: "TRANSPARENCY_DISCLOSURE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "AI Policy Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Responsible AI", href: "/trust/responsible-ai" }],
    sources: [],
    changeSummary: "Disclosures regarding AI mentor recommendation factors, decision provenance, model inputs, and user corrections.",
  },
  "human-oversight": {
    id: "gov-trust-ho-001",
    title: "Human Oversight & Decision Boundaries",
    slug: "trust/human-oversight",
    category: "TRUST",
    documentType: "POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Chief Operating Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Automated Hiring Alignment", href: "/regulatory/automated-hiring" }],
    sources: [],
    changeSummary: "Delineates low-impact guidance assistance from consequential employment/education decisions requiring human oversight.",
  },
  "data-ethics": {
    id: "gov-trust-de-001",
    title: "Data Ethics & Minimisation Standard",
    slug: "trust/data-ethics",
    category: "TRUST",
    documentType: "DATA_ETHICS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Chief Data Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Privacy Policy", href: "/legal/privacy" }],
    sources: [],
    changeSummary: "Data minimisation principles, private Twin access grants, and prohibition of shadow candidate dossiers or ad broker sales.",
  },
  "fairness-and-bias": {
    id: "gov-trust-fb-001",
    title: "Fairness, Algorithmic Parity & Bias Mitigation",
    slug: "trust/fairness-and-bias",
    category: "TRUST",
    documentType: "FAIRNESS_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Algorithmic Fairness Research Lead",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Anti-Discrimination Standard", href: "/standards/anti-discrimination" }],
    sources: [],
    changeSummary: "Bias mitigation testing, pathway parity (university/trades/apprenticeships), protected characteristics, and continuous fairness evaluation.",
  },
  "safeguarding": {
    id: "gov-trust-sg-001",
    title: "Minor Safeguarding & Youth Protection Framework",
    slug: "trust/safeguarding",
    category: "TRUST",
    documentType: "SAFEGUARDING_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Youth Safeguarding Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Student Terms of Service", href: "/legal/student-terms" }, { title: "Parent & Guardian Notice", href: "/legal/parent-guardian-notice" }],
    sources: [],
    changeSummary: "Canonical age model alignment, default-private minor profiles, employer contact hard-blocks, anti-grooming rules, and emergency escalations.",
  },
  "security": {
    id: "gov-trust-sec-001",
    title: "Security Architecture & Controls Matrix",
    slug: "trust/security",
    category: "TRUST",
    documentType: "SECURITY_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States Infrastructure",
    owner: "Head of Infrastructure Security",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Approved Subprocessors", href: "/legal/subprocessors" }],
    sources: [],
    changeSummary: "Rebuilt security disclosures with verified control states matrix (IMPLEMENTED, IN_PROGRESS, PLANNED) and PostgreSQL RLS authorization details.",
  },
  "trust-accessibility": {
    id: "gov-trust-a11y-001",
    title: "Product Accessibility Standards & Design",
    slug: "trust/accessibility",
    category: "TRUST",
    documentType: "ACCESSIBILITY_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Frontend Engineering Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Web Accessibility Statement", href: "/legal/accessibility" }],
    sources: [],
    changeSummary: "Product design principles, keyboard navigation, screen readers, contrast, reduced motion, and AI interface accessibility.",
  },
  "verification": {
    id: "gov-trust-ver-001",
    title: "Evidence Verification Taxonomy & Passport Spectrum",
    slug: "trust/verification",
    category: "TRUST",
    documentType: "VERIFICATION_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Credential Infrastructure Lead",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "General Terms of Service", href: "/legal/terms" }],
    sources: [],
    changeSummary: "Explains 9 verification states (SELF_DECLARED to EMPLOYER_VERIFIED to DISPUTED) and issuer provenance rules.",
  },
  "transparency": {
    id: "gov-trust-tra-001",
    title: "Corporate Disclosures & Roadmap Transparency",
    slug: "trust/transparency",
    category: "TRUST",
    documentType: "TRANSPARENCY_DISCLOSURE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Corporate Governance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Legal Version History", href: "/legal/version-history" }],
    sources: [],
    changeSummary: "Public disclosures distinguishing deployed capabilities from planned features, commercial partnerships, and regulatory readiness posture.",
  },

  // PART B — STANDARDS CENTER
  "standards-hub": {
    id: "gov-std-hub-001",
    title: "Career OS Platform Conduct Standards Hub",
    slug: "standards",
    category: "STANDARDS",
    documentType: "GOVERNANCE_HUB",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Trust & Safety Director",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Community Code", href: "/standards/community-code" }, { title: "Employer Ethical Code", href: "/standards/employer-code" }],
    sources: [],
    changeSummary: "Central directory delineating behavioral platform standards from legal terms and regulatory alignment.",
  },
  "community-code": {
    id: "gov-std-com-001",
    title: "Community Code of Conduct",
    slug: "standards/community-code",
    category: "STANDARDS",
    documentType: "CODE_OF_CONDUCT",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Community Safety Manager",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Acceptable Use Policy", href: "/legal/acceptable-use" }],
    sources: [],
    changeSummary: "Respect, professionalism, identity integrity, anti-harassment, anti-doxxing, and safety enforcement.",
  },
  "mentor-code": {
    id: "gov-std-men-001",
    title: "AI & Human Mentor Code of Ethics",
    slug: "standards/mentor-code",
    category: "STANDARDS",
    documentType: "ETHICAL_CODE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Mentorship Standards Director",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "AI System Usage Terms", href: "/legal/ai-terms" }],
    sources: [],
    changeSummary: "AI mentor identity disclosures, prohibition of dependency engineering/romantic framing, evidence-based recommendations, and safeguarding escalations.",
  },
  "employer-code": {
    id: "gov-std-emp-001",
    title: "Employer & Recruiter Ethical Hiring Code",
    slug: "standards/employer-code",
    category: "STANDARDS",
    documentType: "ETHICAL_CODE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Enterprise Integrity Lead",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    requiresEmploymentCounselReview: true,
    relatedDocuments: [{ title: "Employer Terms of Service", href: "/legal/employer-terms" }],
    sources: [],
    changeSummary: "Verified corporate identity, authentic job postings, compensation transparency, candidate privacy grants, and minor safeguarding rules.",
  },
  "opportunity-standards": {
    id: "gov-std-opp-001",
    title: "Authentic Opportunity & Compensation Standards",
    slug: "standards/opportunity-standards",
    category: "STANDARDS",
    documentType: "QUALITY_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Opportunity Quality Director",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Employer Ethical Code", href: "/standards/employer-code" }],
    sources: [],
    changeSummary: "Standards for employment, internships, apprenticeships, trades, and education; prohibition of advance-fee scams, MLMs, or misleading compensation.",
  },
  "anti-discrimination": {
    id: "gov-std-ad-001",
    title: "Platform Anti-Discrimination Standard",
    slug: "standards/anti-discrimination",
    category: "STANDARDS",
    documentType: "ANTI_DISCRIMINATION_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Diversity & Civil Rights Lead",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Fairness & Bias Mitigation", href: "/trust/fairness-and-bias" }],
    sources: [{ title: "Title VII Civil Rights Act", citation: "42 U.S.C. § 2000e" }],
    changeSummary: "Prohibitions on protected-characteristic targeting, proxy variable discrimination, and requirements for candidate accessibility accommodations.",
  },
  "professional-conduct": {
    id: "gov-std-pc-001",
    title: "Professional Conduct & Evidence Integrity Standard",
    slug: "standards/professional-conduct",
    category: "STANDARDS",
    documentType: "CONDUCT_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Professional Standards Committee",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Acceptable Use Policy", href: "/legal/acceptable-use" }],
    sources: [],
    changeSummary: "Authenticity of qualifications, reference integrity, employer trade secret protection, and transparent AI-assisted job applications.",
  },
  "safety": {
    id: "gov-std-saf-001",
    title: "Cross-Platform Safety Standard",
    slug: "standards/safety",
    category: "STANDARDS",
    documentType: "SAFETY_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Chief Safety Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [{ title: "Minor Safeguarding Framework", href: "/trust/safeguarding" }],
    sources: [],
    changeSummary: "Cross-platform safety standard covering students, professionals, schools, employers, and network users.",
  },

  // PART C — REGULATORY ALIGNMENT CENTER
  "regulatory-hub": {
    id: "gov-reg-hub-001",
    title: "Regulatory Alignment & Readiness Hub",
    slug: "regulatory",
    category: "REGULATORY",
    documentType: "GOVERNANCE_HUB",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & Global",
    owner: "Regulatory Affairs Director",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "US Regulatory Overview", href: "/regulatory/united-states" }],
    sources: [],
    changeSummary: "Central hub for regulatory alignment frameworks across student privacy, automated hiring, fair employment, and state privacy laws.",
  },
  "united-states": {
    id: "gov-reg-us-001",
    title: "United States Regulatory Map & Relevance Matrix",
    slug: "regulatory/united-states",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Student Privacy Alignment", href: "/regulatory/student-privacy" }],
    sources: [],
    changeSummary: "US regulatory map categorizing federal and state statutes across explicit legal relevance states (APPLIES, MAY_APPLY, FEATURE_DEPENDENT).",
  },
  "student-privacy": {
    id: "gov-reg-student-privacy-001",
    title: "Student Privacy Regulatory Alignment (FERPA / COPPA)",
    slug: "regulatory/student-privacy",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States Federal & State Statutes",
    owner: "Education Privacy Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "School Terms of Service", href: "/legal/school-terms" }],
    sources: [{ title: "FERPA", citation: "20 U.S.C. § 1232g" }, { title: "COPPA", citation: "15 U.S.C. §§ 6501–6506" }],
    changeSummary: "Detailed readiness framework for FERPA school-official exception, COPPA institutional consent, and state student privacy statutes.",
  },
  "student-assessments": {
    id: "gov-reg-ppra-001",
    title: "Student Assessments & PPRA Alignment Framework",
    slug: "regulatory/student-assessments",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (20 U.S.C. § 1232h)",
    owner: "Education Compliance Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Student Privacy Alignment", href: "/regulatory/student-privacy" }],
    sources: [{ title: "PPRA", citation: "20 U.S.C. § 1232h" }],
    changeSummary: "Protection of Pupil Rights Amendment (PPRA) analysis for school-administered career interest surveys and assessment data minimisation.",
  },
  "youth-employment": {
    id: "gov-reg-ye-001",
    title: "Youth Employment Laws & Opportunity Safeguards",
    slug: "regulatory/youth-employment",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (FLSA & State Labor Law)",
    owner: "Employment Compliance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Employer Ethical Code", href: "/standards/employer-code" }],
    sources: [{ title: "FLSA Child Labor Provisions", citation: "29 U.S.C. § 212" }],
    changeSummary: "Federal and state youth employment laws, maximum hours, hazardous occupation prohibitions, and work permit verification frameworks.",
  },
  "fair-employment": {
    id: "gov-reg-fe-001",
    title: "Federal Fair Employment & Anti-Discrimination Framework",
    slug: "regulatory/fair-employment",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States Federal (EEOC)",
    owner: "EEOC Compliance Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Anti-Discrimination Standard", href: "/standards/anti-discrimination" }],
    sources: [{ title: "Title VII Civil Rights Act", citation: "42 U.S.C. § 2000e" }, { title: "ADA", citation: "42 U.S.C. § 12101" }],
    changeSummary: "Federal EEOC framework alignment, disability accommodation, job applicant transparency, and employer responsibility.",
  },
  "automated-hiring": {
    id: "gov-reg-aedt-001",
    title: "Automated Employment Decision Tools (AEDT) Alignment",
    slug: "regulatory/automated-hiring",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "New York City, California, Colorado & EU",
    owner: "Employment AI Compliance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Employer Terms of Service", href: "/legal/employer-terms" }],
    sources: [{ title: "NYC Local Law 144", citation: "NYC Admin Code § 20-870" }, { title: "EU AI Act", citation: "Regulation (EU) 2024/1689" }],
    changeSummary: "NYC LL144 & EU AI Act readiness posture, 7-role AI employment taxonomy, and prohibition of autonomous hiring decisions.",
  },
  "fcra-and-employment-reports": {
    id: "gov-reg-fcra-001",
    title: "FCRA & Background Reporting Scope Analysis",
    slug: "regulatory/fcra-and-employment-reports",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (15 U.S.C. § 1681 et seq.)",
    owner: "FCRA Compliance Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    requiresEmploymentCounselReview: true,
    relatedDocuments: [{ title: "Candidate Privacy Notice", href: "/legal/candidate-privacy" }],
    sources: [{ title: "Fair Credit Reporting Act", citation: "15 U.S.C. § 1681" }],
    changeSummary: "Legal scope analysis explaining non-agency status while establishing FCRA_SCOPE_REVIEW_REQUIRED triggers for future background features.",
  },
  "state-privacy": {
    id: "gov-reg-state-privacy-001",
    title: "US State Comprehensive Consumer Privacy Frameworks",
    slug: "regulatory/state-privacy",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "US State Statutes (CA, VA, CO, CT, UT)",
    owner: "State Privacy Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "Privacy Policy", href: "/legal/privacy" }],
    sources: [{ title: "California CCPA/CPRA", citation: "Cal. Civ. Code § 1798.100" }, { title: "Virginia VCDPA", citation: "Va. Code § 59.1-575" }],
    changeSummary: "Analysis of US state privacy statutes (CCPA, VCDPA, CPA, CTDPA, UCPA), applicability thresholds, consumer rights, and youth opt-in rules.",
  },
  "global-expansion": {
    id: "gov-reg-global-001",
    title: "Global Expansion & International Regulatory Launch Gate",
    slug: "regulatory/global-expansion",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "International (UK, EU, CA, AU)",
    owner: "International Legal Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [{ title: "US Regulatory Overview", href: "/regulatory/united-states" }],
    sources: [{ title: "EU GDPR", citation: "Regulation (EU) 2016/679" }, { title: "UK GDPR / DPA 2018", citation: "Data Protection Act 2018" }],
    changeSummary: "US-first launch strategy and 8-stage international launch gate framework for future expansion to UK, EU, Canada, and Australia.",
  },
};
