import type { GovernanceDocumentMeta } from "@/types/platform/governance";

export interface ExtendedGovernanceMeta extends GovernanceDocumentMeta {
  requiresFounderConfirmation?: boolean;
  requiresPrivacyCounselReview?: boolean;
  requiresEmploymentCounselReview?: boolean;
  requiresEducationCounselReview?: boolean;
  requiresCommercialCounselReview?: boolean;
}

export const GOVERNANCE_MANIFEST: Record<string, ExtendedGovernanceMeta> = {
  // HUB
  "legal-hub": {
    id: "gov-legal-hub-001",
    title: "Career OS Legal & Compliance Centre",
    slug: "legal-hub",
    category: "LEGAL",
    documentType: "GOVERNANCE_HUB",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Delaware & Federal)",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [],
    sources: [],
    changeSummary: "Established complete multi-tenant legal framework covering individuals, youth, schools, employers, and AI systems.",
  },

  // INDIVIDUAL & GENERAL
  "terms": {
    id: "gov-legal-terms-001",
    title: "General Terms of Service",
    slug: "terms",
    category: "LEGAL",
    documentType: "TERMS_OF_SERVICE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "State of Delaware / United States",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresFounderConfirmation: true,
    requiresCommercialCounselReview: true,
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Acceptable Use Policy", href: "/legal/acceptable-use" },
      { title: "AI System Usage Terms", href: "/legal/ai-terms" },
      { title: "Student Terms of Service", href: "/legal/student-terms" },
    ],
    sources: [],
    changeSummary: "Rebuilt terms covering 22 core sections: canonical age model (16+ direct), AI disclaimers, evidence verification spectrum, and user content processing grants.",
  },

  "privacy": {
    id: "gov-legal-privacy-001",
    title: "Career OS Privacy Policy",
    slug: "privacy",
    category: "LEGAL",
    documentType: "PRIVACY_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Chief Privacy Officer",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Parent & Guardian Privacy Notice", href: "/legal/parent-guardian-notice" },
      { title: "Candidate Privacy Notice", href: "/legal/candidate-privacy" },
      { title: "Cookie & Storage Policy", href: "/legal/cookies" },
    ],
    sources: [
      { title: "FERPA (20 U.S.C. § 1232g)", citation: "34 CFR Part 99" },
      { title: "COPPA (15 U.S.C. §§ 6501–6506)", citation: "16 CFR Part 312" },
      { title: "California CCPA/CPRA", citation: "Cal. Civ. Code § 1798.100 et seq." },
    ],
    changeSummary: "Comprehensive privacy notice covering 18 sections: data categories, AI LLM provider boundaries, conditional FERPA school official framework, and retention schedules.",
  },

  "cookies": {
    id: "gov-legal-cookies-001",
    title: "Cookie & Browser Storage Policy",
    slug: "cookies",
    category: "LEGAL",
    documentType: "COOKIE_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & Global",
    owner: "Data Privacy Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Security Architecture", href: "/trust/security" },
    ],
    sources: [],
    changeSummary: "Inventory of deployed application storage (Supabase auth JWTs, workspace state, consent timestamps); zero 3rd-party ad tracking pixels.",
  },

  "acceptable-use": {
    id: "gov-legal-aup-001",
    title: "Acceptable Use Policy",
    slug: "acceptable-use",
    category: "LEGAL",
    documentType: "ACCEPTABLE_USE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global Infrastructure",
    owner: "Trust & Safety Director",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [
      { title: "General Terms of Service", href: "/legal/terms" },
      { title: "AI System Usage Terms", href: "/legal/ai-terms" },
      { title: "Community Conduct Code", href: "/standards/community-code" },
    ],
    sources: [],
    changeSummary: "Explicit prohibitions on credential fabrication, AI evidence forgery, candidate scraping, and discriminatory employer targeting.",
  },

  "ai-terms": {
    id: "gov-legal-ai-terms-001",
    title: "AI System Usage Terms & Disclosure",
    slug: "ai-terms",
    category: "LEGAL",
    documentType: "AI_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & EU Alignment",
    owner: "AI Policy Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [
      { title: "General Terms of Service", href: "/legal/terms" },
      { title: "Responsible AI Policy", href: "/trust/responsible-ai" },
      { title: "AEDT Automated Hiring Readiness", href: "/regulatory/automated-hiring" },
    ],
    sources: [
      { title: "EU Artificial Intelligence Act", citation: "Regulation (EU) 2024/1689" },
    ],
    changeSummary: "Non-human AI system disclosure, system-assigned mentor identity terms, hallucination disclaimers, and provider model isolation rules.",
  },

  // YOUTH & SCHOOLS
  "student-terms": {
    id: "gov-legal-student-terms-001",
    title: "Student & Youth Terms of Service",
    slug: "student-terms",
    category: "LEGAL",
    documentType: "STUDENT_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Education & Safeguarding Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresEducationCounselReview: true,
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Parent & Guardian Notice", href: "/legal/parent-guardian-notice" },
      { title: "School Terms of Service", href: "/legal/school-terms" },
    ],
    sources: [
      { title: "FERPA Eligible Student Transfer Rule", citation: "34 CFR § 99.5" },
    ],
    changeSummary: "Canonical age model alignment (16+ direct account eligibility; 13–15 verified relationship; under-13 institutional); asset separation and FERPA transfer rules.",
  },

  "parent-guardian-notice": {
    id: "gov-legal-parent-notice-001",
    title: "Parent & Guardian Privacy Notice",
    slug: "parent-guardian-notice",
    category: "LEGAL",
    documentType: "PARENT_GUARDIAN_NOTICE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Youth Safeguarding Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    requiresEducationCounselReview: true,
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Minor Safeguarding Framework", href: "/trust/safeguarding" },
    ],
    sources: [
      { title: "COPPA Educational Consent Rule", citation: "16 CFR § 312.5" },
    ],
    changeSummary: "High-trust plain English notice for families explaining age gating, minor recruiter protections, AI safeguards, and FERPA transfer at 18.",
  },

  "school-terms": {
    id: "gov-legal-school-terms-001",
    title: "School & Institutional Terms of Service",
    slug: "school-terms",
    category: "LEGAL",
    documentType: "SCHOOL_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Institutional General Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresEducationCounselReview: true,
    requiresCommercialCounselReview: true,
    relatedDocuments: [
      { title: "Data Processing Addendum", href: "/legal/data-processing" },
      { title: "Institutional DPA Execution Guide", href: "/legal/dpa" },
      { title: "Student Privacy Framework", href: "/regulatory/student-privacy" },
    ],
    sources: [
      { title: "FERPA School Official Exception", citation: "34 CFR § 99.31(a)(1)(i)(B)" },
    ],
    changeSummary: "Institutional terms covering district authorization, conditional FERPA school official framework, roster provisioning, advertising prohibition, and post-graduation transition.",
  },

  // EMPLOYERS & CANDIDATES
  "employer-terms": {
    id: "gov-legal-employer-terms-001",
    title: "Employer & Recruiter Terms of Service",
    slug: "employer-terms",
    category: "LEGAL",
    documentType: "EMPLOYER_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Commercial Legal Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresEmploymentCounselReview: true,
    requiresCommercialCounselReview: true,
    relatedDocuments: [
      { title: "Candidate Privacy Notice", href: "/legal/candidate-privacy" },
      { title: "Employer Ethical Hiring Code", href: "/standards/employer-code" },
      { title: "AEDT Automated Hiring Readiness", href: "/regulatory/automated-hiring" },
    ],
    sources: [
      { title: "EEOC Uniform Guidelines", citation: "29 CFR Part 1607" },
    ],
    changeSummary: "Recruiter terms enforcing verified employer identity, real job posts only, EEOC non-discrimination, candidate PII access grant rules, and minor candidate safeguards.",
  },

  "candidate-privacy": {
    id: "gov-legal-candidate-privacy-001",
    title: "Candidate Privacy Notice",
    slug: "candidate-privacy",
    category: "LEGAL",
    documentType: "CANDIDATE_PRIVACY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Privacy & Employment Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    requiresEmploymentCounselReview: true,
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Employer Terms of Service", href: "/legal/employer-terms" },
    ],
    sources: [],
    changeSummary: "Explains candidate profile visibility controls, Candidate Hash IDs, access grants, matching rationale, and FCRA non-agency scope notice.",
  },

  // DATA PROCESSING & COMPLIANCE
  "data-processing": {
    id: "gov-legal-dpa-001",
    title: "Data Processing Addendum (DPA)",
    slug: "data-processing",
    category: "LEGAL",
    documentType: "DPA",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States & EU Compliance Framework",
    owner: "Privacy Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [
      { title: "School Terms of Service", href: "/legal/school-terms" },
      { title: "Approved Subprocessors", href: "/legal/subprocessors" },
      { title: "Security Architecture", href: "/trust/security" },
    ],
    sources: [],
    changeSummary: "Standardized B2B/institutional DPA framework with controller/processor obligations, security annexes, and subprocessor notification rules.",
  },

  "dpa": {
    id: "gov-legal-dpa-guide-001",
    title: "Institutional DPA Execution Guide",
    slug: "dpa",
    category: "LEGAL",
    documentType: "DPA_GUIDE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Institutional Sales & Compliance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Data Processing Addendum", href: "/legal/data-processing" },
      { title: "School Terms of Service", href: "/legal/school-terms" },
    ],
    sources: [],
    changeSummary: "Guide for district administrators on executing Career OS model DPAs (CA CSPA, NY Exhibit E, IL SDPC).",
  },

  "copyright": {
    id: "gov-legal-copyright-001",
    title: "Copyright & Intellectual Property Policy",
    slug: "copyright",
    category: "LEGAL",
    documentType: "COPYRIGHT_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (17 U.S.C. § 512)",
    owner: "IP Counsel",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    requiresCommercialCounselReview: true,
    relatedDocuments: [
      { title: "General Terms of Service", href: "/legal/terms" },
      { title: "Acceptable Use Policy", href: "/legal/acceptable-use" },
    ],
    sources: [
      { title: "Digital Millennium Copyright Act", citation: "17 U.S.C. § 512" },
    ],
    changeSummary: "DMCA takedown procedure, counter-notice framework, repeat infringer policy, and AI-generated evidence IP rules.",
  },

  "accessibility": {
    id: "gov-legal-a11y-001",
    title: "Web Accessibility Statement",
    slug: "accessibility",
    category: "LEGAL",
    documentType: "ACCESSIBILITY_STATEMENT",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global Standard (WCAG 2.2 AA)",
    owner: "Accessibility & Frontend Engineering Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Accessibility Trust Standard", href: "/trust/accessibility" },
    ],
    sources: [
      { title: "Web Content Accessibility Guidelines 2.2", citation: "W3C Recommendation (WCAG 2.2 AA)" },
    ],
    changeSummary: "WCAG 2.2 Level AA target commitment, keyboard navigation design, screen reader testing, and remediation reporting process.",
  },

  "subprocessors": {
    id: "gov-legal-subprocessors-001",
    title: "Approved Subprocessor List",
    slug: "subprocessors",
    category: "LEGAL",
    documentType: "SUBPROCESSOR_LIST",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Security & Infrastructure Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Data Processing Addendum", href: "/legal/data-processing" },
      { title: "Privacy Policy", href: "/legal/privacy" },
    ],
    sources: [],
    changeSummary: "Active inventory of verified infrastructure sub-processors (Supabase, Vercel, Google Cloud, OpenAI, Anthropic).",
  },

  "data-retention": {
    id: "gov-legal-retention-001",
    title: "Data Retention Schedule & Principles",
    slug: "data-retention",
    category: "LEGAL",
    documentType: "RETENTION_SCHEDULE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Data Governance Committee",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    requiresPrivacyCounselReview: true,
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "School Terms of Service", href: "/legal/school-terms" },
    ],
    sources: [],
    changeSummary: "Data classification retention rules across accounts, Twin assets, chat logs, school records, and backup purge schedules.",
  },

  "version-history": {
    id: "gov-legal-versions-001",
    title: "Legal Centre Version History & Archive",
    slug: "version-history",
    category: "LEGAL",
    documentType: "VERSION_HISTORY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "Legal Operations Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "General Terms of Service", href: "/legal/terms" },
      { title: "Privacy Policy", href: "/legal/privacy" },
    ],
    sources: [],
    changeSummary: "Archive index of active and superseded governance document versions.",
  },

  // TRUST & REGULATORY PAGES
  "security": {
    id: "gov-trust-security-001",
    title: "Security Controls & Architecture Disclosures",
    slug: "trust/security",
    category: "TRUST",
    documentType: "TECHNICAL_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States Infrastructure",
    owner: "Head of Infrastructure Security",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Approved Subprocessors", href: "/legal/subprocessors" },
    ],
    sources: [],
    changeSummary: "Security controls matrix with verified implementation states and PostgreSQL Row-Level Security authorization disclosures.",
  },

  "safeguarding": {
    id: "gov-trust-safeguarding-001",
    title: "Minor Safeguarding & Youth Safety Framework",
    slug: "trust/safeguarding",
    category: "TRUST",
    documentType: "SAFEGUARDING_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Youth Safeguarding Director",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Parent & Guardian Notice", href: "/legal/parent-guardian-notice" },
    ],
    sources: [],
    changeSummary: "Comprehensive minor safeguarding policies, recruiter contact controls, and escalation channels.",
  },

  "transparency": {
    id: "gov-trust-transparency-001",
    title: "Algorithmic Transparency & Model Disclosures",
    slug: "trust/transparency",
    category: "TRUST",
    documentType: "TRANSPARENCY_DISCLOSURE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global",
    owner: "AI Governance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "AI System Usage Terms", href: "/legal/ai-terms" },
    ],
    sources: [],
    changeSummary: "Disclosures regarding AI mentor recommendation factors and decision support models.",
  },

  "automated-hiring": {
    id: "gov-reg-aedt-001",
    title: "Automated Employment Decision Tools (AEDT) Alignment",
    slug: "regulatory/automated-hiring",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "New York City & EU Regulatory Alignment",
    owner: "Employment AI Compliance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Employer Terms of Service", href: "/legal/employer-terms" },
      { title: "Candidate Privacy Notice", href: "/legal/candidate-privacy" },
    ],
    sources: [
      { title: "NYC Local Law 144 of 2021", citation: "NYC Admin Code § 20-870 et seq." },
      { title: "EU Artificial Intelligence Act", citation: "Regulation (EU) 2024/1689 Annex III" },
    ],
    changeSummary: "NYC LL144 & EU AI Act readiness posture, 7-role AI employment taxonomy, and prohibition of autonomous hiring decisions.",
  },

  "student-privacy": {
    id: "gov-reg-student-privacy-001",
    title: "Student Privacy Regulatory Alignment & Readiness",
    slug: "regulatory/student-privacy",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States Federal & State Statutes",
    owner: "Education Privacy Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "School Terms of Service", href: "/legal/school-terms" },
      { title: "Data Processing Addendum", href: "/legal/data-processing" },
    ],
    sources: [
      { title: "FERPA", citation: "20 U.S.C. § 1232g" },
      { title: "COPPA", citation: "15 U.S.C. §§ 6501–6506" },
      { title: "PPRA", citation: "20 U.S.C. § 1232h" },
    ],
    changeSummary: "7-section readiness framework detailing FERPA school-official exception, COPPA institutional consent, PPRA compliance, and state student privacy alignment.",
  },

  "responsible-hiring": {
    id: "gov-employers-hiring-001",
    title: "Responsible & Ethical Hiring Readiness Standard",
    slug: "employers/responsible-hiring",
    category: "REGULATORY",
    documentType: "ETHICAL_STANDARD",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Ethical Hiring Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Employer Terms of Service", href: "/legal/employer-terms" },
    ],
    sources: [],
    changeSummary: "Ethical guidelines for recruiters using AI matching support.",
  },

  "united-states": {
    id: "gov-reg-us-001",
    title: "United States Federal & State Regulatory Overview",
    slug: "regulatory/united-states",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
    ],
    sources: [],
    changeSummary: "US regulatory overview covering federal privacy and state consumer protection statutes.",
  },
};
