import type { GovernanceDocumentMeta } from "@/types/platform/governance";

export const GOVERNANCE_MANIFEST: Record<string, GovernanceDocumentMeta> = {
  // LEGAL
  "privacy": {
    id: "gov-legal-privacy-001",
    title: "Career OS Privacy Policy",
    slug: "privacy",
    category: "LEGAL",
    documentType: "PRIVACY_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Chief Legal Officer",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Parent & Guardian Notice", href: "/legal/parent-guardian-notice" },
      { title: "Data Processing Addendum", href: "/legal/data-processing" },
    ],
    sources: [
      { title: "FERPA (20 U.S.C. § 1232g)", citation: "34 CFR Part 99" },
      { title: "COPPA (15 U.S.C. §§ 6501–6506)", citation: "16 CFR Part 312" },
      { title: "California CCPA/CPRA", citation: "Cal. Civ. Code § 1798.100 et seq." },
    ],
    changeSummary: "Updated age model alignment (Age 16+ direct account eligibility; Age 13–15 verified relationship requirement; Under-13 school official exception structure) and FERPA transfer rules.",
  },
  "student-terms": {
    id: "gov-legal-student-terms-001",
    title: "Student & Youth Terms of Service",
    slug: "student-terms",
    category: "LEGAL",
    documentType: "STUDENT_TERMS",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Legal Counsel & Student Safeguarding Lead",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "School Terms of Service", href: "/legal/school-terms" },
    ],
    sources: [
      { title: "FERPA Eligible Student Transfer Rule", citation: "34 CFR § 99.5" },
    ],
    changeSummary: "Corrected parent/eligible-student FERPA rights transfer rules and distinguished user-created Career Twin assets from school-owned education records.",
  },
  "terms": {
    id: "gov-legal-terms-001",
    title: "General Terms of Service",
    slug: "terms",
    category: "LEGAL",
    documentType: "TERMS_OF_SERVICE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States / Delaware",
    owner: "General Counsel",
    requiresLegalReview: true,
    bindingStatus: "BINDING",
    relatedDocuments: [
      { title: "Privacy Policy", href: "/legal/privacy" },
      { title: "Acceptable Use Policy", href: "/legal/acceptable-use" },
    ],
    sources: [],
    changeSummary: "Updated direct account minimum age to 16 and separated account eligibility from legal majority.",
  },

  // REGULATORY
  "student-privacy": {
    id: "gov-reg-student-privacy-001",
    title: "Student Privacy — Regulatory Alignment & Readiness",
    slug: "student-privacy",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (Federal & State)",
    owner: "Regulatory Compliance Director",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Institutional Data Protection Agreement", href: "/legal/dpa" },
    ],
    sources: [
      { title: "FERPA", citation: "20 U.S.C. § 1232g; 34 CFR Part 99" },
      { title: "COPPA", citation: "15 U.S.C. §§ 6501–6506; 16 CFR Part 312" },
      { title: "SOPIPA (California)", citation: "Cal. Bus. & Prof. Code §§ 22584-22585" },
    ],
    changeSummary: "Reframed compliance posture to Regulatory Alignment & Readiness; structured into 7 core analytical sections.",
  },
  "automated-hiring": {
    id: "gov-reg-automated-hiring-001",
    title: "Automated Employment Decision Tools — Regulatory Alignment & Readiness",
    slug: "automated-hiring",
    category: "REGULATORY",
    documentType: "REGULATORY_FRAMEWORK",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States (NYC, States) & EU",
    owner: "AI Policy & Governance Lead",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Employer Ethical Hiring Code", href: "/standards/employer-code" },
      { title: "Fairness & Bias Mitigation Standards", href: "/trust/fairness-and-bias" },
    ],
    sources: [
      { title: "NYC Local Law 144", citation: "NYC Admin Code § 20-870 et seq." },
      { title: "EU Artificial Intelligence Act", citation: "Regulation (EU) 2024/1689 (High-Risk Employment AI)" },
      { title: "EEOC Uniform Guidelines", citation: "29 CFR Part 1607" },
    ],
    changeSummary: "Removed unsupported audit completion claims; introduced Employment AI Role Taxonomy and readiness framework.",
  },

  // TRUST
  "security": {
    id: "gov-trust-security-001",
    title: "Platform Security Architecture & Controls Matrix",
    slug: "security",
    category: "TRUST",
    documentType: "SECURITY_ARCHITECTURE",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "Global Infrastructure",
    owner: "Chief Information Security Officer",
    requiresLegalReview: true,
    bindingStatus: "INFORMATIONAL",
    relatedDocuments: [
      { title: "Data Sovereignty Standards", href: "/trust/data-ethics" },
      { title: "Privacy Policy", href: "/legal/privacy" },
    ],
    sources: [
      { title: "NIST Cybersecurity Framework 2.0", citation: "NIST CSWP 29" },
    ],
    changeSummary: "Audited public claims; introduced Security Control States (IMPLEMENTED, IN_PROGRESS, PLANNED) and clarified PostgreSQL RLS access control mechanism.",
  },
  "safeguarding": {
    id: "gov-trust-safeguarding-001",
    title: "Minor Safeguarding & Youth Protection Framework",
    slug: "safeguarding",
    category: "TRUST",
    documentType: "SAFEGUARDING_POLICY",
    version: "2026.08.1",
    status: "ACTIVE",
    effectiveDate: "2026-08-17",
    publishedDate: "2026-08-17",
    lastReviewedDate: "2026-08-17",
    nextReviewDate: "2027-08-17",
    jurisdiction: "United States",
    owner: "Youth Safeguarding Officer",
    requiresLegalReview: true,
    bindingStatus: "POLICY",
    relatedDocuments: [
      { title: "Student Terms of Service", href: "/legal/student-terms" },
      { title: "Student Privacy Framework", href: "/regulatory/student-privacy" },
    ],
    sources: [],
    changeSummary: "Strengthened minor employer contact safeguarding rules (no unrestricted browsing, default-private profiles, institution-controlled programs).",
  },
};
