import React from 'react';
import { EditorialSubpage } from '@/components/layout/EditorialSubpage';
import { ROUTES } from '@/lib/routes';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Ai Transparency — Trust | Career OS",
  description: "Career OS Trust ai Transparency. Verified evidence, persistent career intelligence, and absolute privacy.",
  alternates: {
    canonical: "https://career-os.com/trust/ai-transparency",
  },
};

export default function TrustAiTransparencyPage() {
  return (
    <EditorialSubpage
      badge="TRUST &bull; AI TRANSPARENCY"
      title="AI Model Transparency & Factor Provenance"
      description="Understand how AI Career Mentor and Opportunity Agent generate recommendations, compute capability matches, and explain every output."
      breadcrumbs={[
        { label: 'Home', href: ROUTES.HOME },
        { label: 'Trust', href: ROUTES.TRUST },
        { label: 'AI Transparency', href: ROUTES.TRUST_AI_TRANSPARENCY },
      ]}
      lastUpdated="August 2026"
    >
      <div className="space-y-6">
        <h2 className="text-xl font-bold text-[var(--color-text-primary)]">Explainability by Design</h2>
        <p>
          Career OS rejects opaque algorithmic scoring. Every recommendation generated by our AI Mentor and matching engines is accompanied by deterministic factor provenance, outlining precisely which evidence points influenced the output.
        </p>

        <h3 className="text-lg font-bold text-[var(--color-text-primary)] pt-4">Transparency Commitments</h3>
        <ul className="space-y-2 list-disc pl-5">
          <li><strong>No Hidden Scoring:</strong> Users have direct access to inspect their complete Career Twin capability graph and see how it is evaluated.</li>
          <li><strong>Inspectable Prompt Context:</strong> Clear disclosure of the grounding context provided to foundation models during mentor sessions.</li>
          <li><strong>Correction & Feedback:</strong> Immediate ability for users to correct misconceptions or prune obsolete skills from their active model.</li>
        </ul>
      </div>
    </EditorialSubpage>
  );
}
