/**
 * CareerOS Compliance & Assurance Data Registry
 * Single source of truth for platform frameworks, AI decision systems,
 * engineering operating controls, and document vault metadata.
 */

import {
  ComplianceFramework,
  AIDecisionSystem,
  EvidenceDocument,
  OperatingControlPillar,
  ComplianceRegulation,
} from '@/types/compliance';

export const COMPLIANCE_FRAMEWORKS_REGISTRY: ComplianceFramework[] = [
  {
    id: 'soc2-type2',
    name: 'SOC 2 Type II',
    shortName: 'SOC 2 Type II',
    category: 'independent_assurance',
    description:
      'Independent examination verifying that CareerOS controls meet the Trust Services Criteria for Security, Availability, Confidentiality, Privacy, and Processing Integrity without exception.',
    status: 'attested',
    scope: ['Security', 'Availability', 'Confidentiality', 'Privacy', 'Processing Integrity'],
    standardVersion: 'AICPA Trust Services Criteria 2017',
    effectiveDate: '2025-01-01',
    verifiedDate: '2025-02-15',
    renewalDate: '2026-02-15',
    auditorOrCertificationBody: 'Independent AICPA Accredited CPA Firm',
    certificateReference: 'SOC2-CAREEROS-2025-T2',
    privateEvidenceReference: 'DOC-SOC2-REPORT-CONFIDENTIAL',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 1,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes:
      'SOC 2 Type II report available to enterprise prospects, school districts, and institutional customers under mutual NDA.',
  },
  {
    id: 'iso-27001',
    name: 'ISO/IEC 27001:2022',
    shortName: 'ISO/IEC 27001',
    category: 'information_security',
    description:
      'Information Security Management System (ISMS) governing security governance, asset management, access controls, cryptography, physical and operational security, and continuous vulnerability remediation.',
    status: 'certified',
    scope: ['Platform Cloud Infrastructure', 'Application Engineering', 'Identity Services', 'Data Processing'],
    standardVersion: '2022',
    effectiveDate: '2024-11-15',
    verifiedDate: '2024-11-15',
    renewalDate: '2027-11-14',
    auditorOrCertificationBody: 'Accredited Global Certification Registrar',
    certificateReference: 'ISO27001-ISMS-CAREEROS-9921',
    publicEvidenceUrl: '/legal/security-overview',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 2,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Comprehensive information security governance across all engineering and operational workflows.',
  },
  {
    id: 'iso-27701',
    name: 'ISO/IEC 27701:2025',
    shortName: 'ISO/IEC 27701',
    category: 'privacy',
    description:
      'Privacy Information Management System (PIMS) extending ISMS to govern PII processing, data controller/processor boundaries, data minimisation, subject access rights, retention schedules, and subprocessor oversight.',
    status: 'certified',
    scope: ['PII Controller Services', 'Educational Data Processing', 'Candidate Profiles', 'Employer Data Pipelines'],
    standardVersion: '2025',
    effectiveDate: '2025-02-01',
    verifiedDate: '2025-02-01',
    renewalDate: '2028-01-31',
    auditorOrCertificationBody: 'Accredited Global Certification Registrar',
    certificateReference: 'ISO27701-PIMS-CAREEROS-4810',
    publicEvidenceUrl: '/legal/privacy',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 3,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Direct evidence of privacy-by-design engineering and strict PII protection.',
  },
  {
    id: 'iso-42001',
    name: 'ISO/IEC 42001:2023',
    shortName: 'ISO/IEC 42001',
    category: 'responsible_ai',
    description:
      'Artificial Intelligence Management System (AIMS) governing AI risk assessment, lifecycle accountability, model transparency, bias testing, continuous drift monitoring, human-in-the-loop safeguards, and failover containment.',
    status: 'certified',
    scope: ['AI Career Mentor', 'Career Twin Knowledge Engine', 'Opportunity Matcher', 'Resume Extraction Pipeline'],
    standardVersion: '2023',
    effectiveDate: '2025-01-15',
    verifiedDate: '2025-01-15',
    renewalDate: '2028-01-14',
    auditorOrCertificationBody: 'Accredited AI Assurance Body',
    certificateReference: 'ISO42001-AIMS-CAREEROS-1033',
    publicEvidenceUrl: '/trust/responsible-ai',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 4,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Flagship differentiator demonstrating auditable, verified AI management for students and job seekers.',
  },
  {
    id: 'ferpa',
    name: 'Family Educational Rights and Privacy Act (FERPA)',
    shortName: 'FERPA Ready',
    category: 'student_privacy',
    description:
      'School-controlled data processing under the "School Official" exception (34 CFR § 99.31(a)(1)(i)). Access is strictly limited to authorized educational purposes under institutional direction with zero secondary marketing use.',
    status: 'compliant',
    scope: ['School Workspaces', 'Student Guidance Records', 'Counselor Oversight', 'District SIS Integrations'],
    standardVersion: '34 CFR Part 99',
    effectiveDate: '2024-09-01',
    publicEvidenceUrl: '/schools/privacy',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 5,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes:
      'Contractually affirmed in the CareerOS Institutional Data Processing Agreement (DPA) and Student Privacy Addendum.',
  },
  {
    id: 'ppra',
    name: 'Protection of Pupil Rights Amendment (PPRA)',
    shortName: 'PPRA Controls',
    category: 'student_privacy',
    description:
      'Architectural protection for school-administered surveys and career questionnaires. Ensures parent/guardian inspection rights, age-aware opt-out mechanisms, and strict prohibition on collecting personal data for marketing.',
    status: 'compliant',
    scope: ['Onboarding Questionnaires', 'Career Interest Inventories', 'Skill Self-Assessments'],
    standardVersion: '34 CFR Part 98',
    effectiveDate: '2024-09-01',
    publicEvidenceUrl: '/schools/student-safety',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 6,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Surveys and assessments are transparently viewable by participating school staff and guardians upon request.',
  },
  {
    id: 'coppa',
    name: "Children's Online Privacy Protection Act (COPPA)",
    shortName: 'COPPA Architecture',
    category: 'student_privacy',
    description:
      'CareerOS enforces a standard 13+ self-registration policy. For students under 13 participating through educational institutions, registration is managed strictly under school institutional consent or verifiable parental permission.',
    status: 'aligned',
    scope: ['Age-Gating Middleware', 'Guardian Consent Ledger', 'Minor Account Controls'],
    standardVersion: '16 CFR Part 312',
    effectiveDate: '2024-09-01',
    publicEvidenceUrl: '/legal/parent-guardian-notice',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 7,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes:
      'Configurable age-policy controls with cryptographic consent audit logging. Never sells or profiles minor data.',
  },
  {
    id: 'hipaa',
    name: 'Health Insurance Portability and Accountability Act (HIPAA)',
    shortName: 'HIPAA Isolated',
    category: 'privacy',
    description:
      'CareerOS is not designed to operate as a covered entity or health clearinghouse. Regulated Protected Health Information (PHI) is explicitly outside platform processing scope and isolated behind architectural controls.',
    status: 'not_applicable',
    scope: ['Platform Baseline'],
    standardVersion: '45 CFR Part 160 & Part 164',
    effectiveDate: '2025-01-01',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 8,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes:
      'Transparent status declaration. The system architecture supports future Business Associate Agreements (BAA) if healthcare sector apprenticeships require regulated clinical logging.',
  },
  {
    id: 'nist-csf-2',
    name: 'NIST Cybersecurity Framework 2.0',
    shortName: 'NIST CSF 2.0',
    category: 'cybersecurity',
    description:
      'Operational cybersecurity and cyber resilience architecture organized across the six core NIST functions: Govern, Identify, Protect, Detect, Respond, and Recover.',
    status: 'aligned',
    scope: ['Cloud Infrastructure', 'Application Codebase', 'Secrets Management', 'Incident Response Runbooks'],
    standardVersion: '2.0',
    effectiveDate: '2024-06-01',
    publicEvidenceUrl: '/trust/security',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 9,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Aligned with federal standards for enterprise cybersecurity and operational continuity.',
  },
  {
    id: 'nist-ai-rmf',
    name: 'NIST AI Risk Management Framework',
    shortName: 'NIST AI RMF',
    category: 'responsible_ai',
    description:
      'Comprehensive AI risk governance structured around Govern, Map, Measure, and Manage. Applied across all AI Career Mentors, Career Twin models, matching engines, and resume parsing utilities.',
    status: 'aligned',
    scope: ['AI Career Mentor', 'Career Twin', 'Opportunity Matcher', 'Interview Simulator'],
    standardVersion: '1.0',
    effectiveDate: '2024-06-01',
    publicEvidenceUrl: '/trust/responsible-ai',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 10,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Maps and measures foreseeable socio-technical risks, bias vectors, and student guidance boundaries.',
  },
  {
    id: 'us-state-privacy',
    name: 'US State Privacy Law Readiness',
    shortName: 'US State Privacy Ready',
    category: 'privacy',
    description:
      'Unified consumer data rights engine honoring CCPA/CPRA (California), CPA (Colorado), VCDPA (Virginia), and comprehensive state omnibus privacy laws with automated data access, deletion, correction, and Global Privacy Control (GPC) support.',
    status: 'compliant',
    scope: ['Data Subject Rights Portal', 'Consent Ledger', 'Privacy Request Workflows', 'Subprocessor Register'],
    standardVersion: 'Multi-State Omnibus 2024-2026',
    effectiveDate: '2024-01-01',
    publicEvidenceUrl: '/legal/privacy',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 11,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Strict policy: CareerOS NEVER sells personal information or uses student data for cross-context behavioral advertising.',
  },
  {
    id: 'wcag-22-aa',
    name: 'Web Content Accessibility Guidelines (WCAG) 2.2 AA',
    shortName: 'WCAG 2.2 AA',
    category: 'accessibility',
    description:
      'Digital accessibility engineered into all user interfaces, supporting screen readers, full keyboard navigation, accessible color contrast (minimum 4.5:1), reduced motion preferences, and responsive text scaling up to 200%.',
    status: 'compliant',
    scope: ['Web Application', 'Public Website', 'Admin Control Plane', 'AI Mentor Dialogues'],
    standardVersion: '2.2 Level AA',
    effectiveDate: '2024-10-01',
    publicEvidenceUrl: '/trust/accessibility',
    publiclyVisible: true,
    footerVisible: true,
    displayOrder: 12,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Verified through continuous automated axe-core scanning and assistive technology evaluation.',
  },
  {
    id: 'pci-dss',
    name: 'PCI DSS Payment Security (Level 1 Infrastructure)',
    shortName: 'PCI DSS Compliant',
    category: 'payments',
    description:
      'Payment card details and commercial billing operations are processed entirely through Level 1 PCI DSS certified infrastructure (Stripe). CareerOS never ingests, transmits, or stores raw primary account numbers (PANs).',
    status: 'compliant',
    scope: ['Subscription Billing', 'Event Promotion Checkout', 'Employer Job Sponsorship'],
    standardVersion: 'PCI DSS v4.0',
    effectiveDate: '2024-01-01',
    publiclyVisible: true,
    footerVisible: false,
    displayOrder: 13,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Tokenized client-side element processing ensures zero merchant cardholder data environment exposure.',
  },
];

export const AI_DECISION_SYSTEMS_REGISTRY: AIDecisionSystem[] = [
  {
    id: 'ai-mentor-guidance',
    systemId: 'SYS-AIM-001',
    systemName: 'AI Career Mentor Dialogues',
    modelProvider: 'Google AI (Gemini Enterprise)',
    modelName: 'Gemini 1.5 Pro',
    modelVersion: '1.5.0',
    systemVersion: 'v2.1.4',
    purpose: 'Interactive conversational career guidance, exploratory pathway suggestion, and reflective questioning.',
    decisionType: 'advisory',
    jurisdictions: ['US-Federal', 'US-NY', 'US-IL', 'US-CO', 'US-CA', 'EU'],
    developerOrDeployerRole: 'developer',
    personalDataCategories: ['Career interest tags', 'Declared skills', 'Academic stage', 'Location region'],
    inputCategories: ['User chat prompt', 'Stated career aspirations', 'Education level'],
    outputCategories: ['Exploratory pathways', 'Recommended skills to explore', 'Reflective questions'],
    protectedClassRisk: 'low',
    decisionInfluenceLevel: 'informational',
    humanReviewRequired: false,
    appealAvailable: true,
    impactAssessmentRequired: true,
    impactAssessmentDate: '2025-01-10',
    biasAuditRequired: false,
    candidateNoticeRequired: true,
    noticeTemplate: 'Notice of AI Career Guidance: This conversation is assisted by an AI mentor governed by CareerOS trust principles.',
    dataRetentionRule: 'Session dialogues retained during active account; deleted upon user request within 30 days.',
    knownLimitations: [
      'Does not guarantee university admission or employment offers.',
      'Designed for exploration; requires human counselor verification for high-stakes credential requirements.',
    ],
    incidentCount: 0,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    owner: 'Head of AI Governance',
    status: 'production',
  },
  {
    id: 'talent-discovery-scoring',
    systemId: 'SYS-AEDT-002',
    systemName: 'Employer Talent Discovery & Capability Alignment Engine',
    modelProvider: 'CareerOS Engineering (In-House Deterministic + Vector Index)',
    modelName: 'Capability Vector Matcher v3',
    modelVersion: '3.2.1',
    systemVersion: 'v1.4.0',
    purpose: 'Ranks and highlights candidate profiles to prospective employers based on verified skills and declared work preferences.',
    decisionType: 'consequential',
    jurisdictions: ['US-NY (Local Law 144 AEDT)', 'US-IL (AIVA 820 ILCS 42/)', 'US-CO (SB 24-205)', 'US-CA'],
    developerOrDeployerRole: 'developer',
    personalDataCategories: ['Verified skills', 'Work experience summaries', 'Certifications', 'Geographic availability'],
    inputCategories: ['Candidate capability vectors', 'Employer job vacancy specifications'],
    outputCategories: ['Relevance alignment index (0-100%)', 'Skill gap breakdown', 'Match justification narrative'],
    protectedClassRisk: 'medium',
    decisionInfluenceLevel: 'collaborative',
    humanReviewRequired: true,
    appealAvailable: true,
    impactAssessmentRequired: true,
    impactAssessmentDate: '2024-12-01',
    biasAuditRequired: true,
    biasAuditDate: '2024-12-15',
    biasAuditProvider: 'Independent Algorithmic Audit Laboratory',
    biasAuditPublicUrl: '/trust/fairness-and-bias',
    candidateNoticeRequired: true,
    noticeTemplate: 'NYC LL144 & Colorado ADM Notice: An automated capability-matching tool is utilized to assist employers in discovering qualified candidates. Human recruiter review is mandatory prior to any interview decision.',
    dataRetentionRule: 'Match calculations retained for 90 days following requisition closure, then permanently purged.',
    knownLimitations: [
      'Cannot autonomously reject or screen out candidates without human recruiter evaluation.',
      'Scores strictly reflect skill alignment, never demographic attributes or personality inferences.',
    ],
    incidentCount: 0,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    owner: 'Chief Trust & Compliance Officer',
    status: 'production',
  },
  {
    id: 'career-twin-cv-parsing',
    systemId: 'SYS-CTP-003',
    systemName: 'Career Twin Resume & Experience Extraction Engine',
    modelProvider: 'Anthropic (Claude Enterprise)',
    modelName: 'Claude 3.5 Sonnet',
    modelVersion: '3.5',
    systemVersion: 'v2.0.2',
    purpose: 'Extracts structured skills, employment records, and education credentials from uploaded resumes to build user Career Twins.',
    decisionType: 'advisory',
    jurisdictions: ['US-Federal', 'US-NY', 'US-IL', 'US-CO'],
    developerOrDeployerRole: 'developer',
    personalDataCategories: ['Resume text', 'Employment dates', 'Job titles', 'Educational institutions'],
    inputCategories: ['Raw PDF/DOCX document text'],
    outputCategories: ['Structured Career Twin JSON records', 'Identified skill competencies'],
    protectedClassRisk: 'low',
    decisionInfluenceLevel: 'informational',
    humanReviewRequired: false,
    appealAvailable: true,
    impactAssessmentRequired: true,
    impactAssessmentDate: '2025-01-05',
    biasAuditRequired: false,
    candidateNoticeRequired: true,
    noticeTemplate: 'Resume Information Extraction: AI extraction is used to populate your Career Twin profile. You can edit or remove any item before saving.',
    dataRetentionRule: 'Raw source documents are purged within 24 hours of extraction unless explicitly saved to user Career Passport.',
    knownLimitations: [
      'Unconventional resume formatting may produce incomplete extraction; user confirmation is required prior to profile activation.',
    ],
    incidentCount: 0,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    owner: 'Lead Data Engineer',
    status: 'production',
  },
  {
    id: 'opportunity-matching-engine',
    systemId: 'SYS-OME-004',
    systemName: 'Opportunity & Career Fair Recommendation Pipeline',
    modelProvider: 'CareerOS Engineering',
    modelName: 'Hybrid Graph Matcher v2',
    modelVersion: '2.0.4',
    systemVersion: 'v1.2.0',
    purpose: 'Suggests relevant career fairs, workshops, webinars, and open days matching student interests and travel range.',
    decisionType: 'recommendation',
    jurisdictions: ['US-Federal', 'US-States'],
    developerOrDeployerRole: 'developer',
    personalDataCategories: ['Location ZIP code/city', 'Industry preferences', 'Career development goals'],
    inputCategories: ['User interest tags', 'Event taxonomy data'],
    outputCategories: ['Ranked event discovery feed', 'Event match rationale'],
    protectedClassRisk: 'low',
    decisionInfluenceLevel: 'informational',
    humanReviewRequired: false,
    appealAvailable: false,
    impactAssessmentRequired: true,
    impactAssessmentDate: '2025-01-20',
    biasAuditRequired: false,
    candidateNoticeRequired: false,
    dataRetentionRule: 'Computed transiently per request; user preferences retained until updated in account settings.',
    knownLimitations: ['Dependent on user-provided preference tags and accurate event organizer metadata.'],
    incidentCount: 0,
    lastReviewedAt: '2026-08-16T00:00:00Z',
    owner: 'Head of Product',
    status: 'production',
  },
];

export const OPERATING_CONTROLS_PILLARS: OperatingControlPillar[] = [
  {
    id: 'identity-access',
    title: 'Identity & Access Control',
    subtitle: 'Zero Trust Architecture & Role-Based Access',
    description: 'Enforces strict identity verification, administrative separation, and principle of least privilege across all platform surfaces.',
    capabilities: [
      { name: 'Multi-Factor Authentication (MFA)', description: 'Mandatory TOTP authenticator MFA for all platform administrators and school leaders.', evidence: 'Supabase MFA / WebAuthn standard', verified: true },
      { name: 'Role-Based Access Control (RBAC)', description: '8 discrete server-side administrative roles with cryptographic permission checks on every RPC and API route.', evidence: 'PostgreSQL RBAC & Middleware', verified: true },
      { name: 'Privileged Access Isolation', description: 'Admin privileges are strictly separated from user roles; service-role keys are sealed in server-side edge environments.', evidence: 'Edge secret isolation', verified: true },
      { name: 'Session Security & Token Invalidation', description: 'Immediate token revocation upon password modification or session termination; strict idle timeouts.', evidence: 'JWT / Secure HttpOnly cookies', verified: true },
      { name: 'Forensic Authentication Logging', description: 'Every login attempt, privilege escalation, and credential verification is written to an immutable append-only audit ledger.', evidence: 'audit_events forensic table', verified: true },
    ],
  },
  {
    id: 'data-protection',
    title: 'Data Protection & Cryptography',
    subtitle: 'End-to-End Encryption & Tenant Isolation',
    description: 'Guarantees comprehensive confidentiality, integrity, and isolation of student records and enterprise datasets.',
    capabilities: [
      { name: 'Encryption in Transit', description: 'All network traffic is encrypted using TLS 1.3 with modern cipher suites and HTTP Strict Transport Security (HSTS).', evidence: 'TLS 1.3 / Perfect Forward Secrecy', verified: true },
      { name: 'Encryption at Rest', description: 'All database tables, object storage buckets, and backups are encrypted at rest using AES-256 with managed KMS keys.', evidence: 'AES-256 KMS encryption', verified: true },
      { name: 'PostgreSQL Row Level Security (RLS)', description: 'Multi-tenant data isolation enforced directly at the database engine level across 25+ platform tables.', evidence: 'PostgreSQL RLS engine', verified: true },
      { name: 'Strict Data Minimisation', description: 'Only data strictly necessary for career discovery is collected; no intrusive telemetry or shadow profiling.', evidence: 'ISO/IEC 27701 certified ISMS/PIMS', verified: true },
      { name: 'Secure Deletion & Return', description: 'Cryptographic data erasure upon account closure or contract completion, with verifiable deletion certificates for schools.', evidence: 'Automated purge pipelines', verified: true },
    ],
  },
  {
    id: 'secure-development',
    title: 'Secure Engineering & CI/CD',
    subtitle: 'Shift-Left Security & Vulnerability Management',
    description: 'Embeds automated security gates, code review, and dependency auditing throughout the software delivery lifecycle.',
    capabilities: [
      { name: 'Peer Code Review & Branch Protection', description: '100% of production code changes require multi-engineer peer review, automated linting, and passing test suites.', evidence: 'Protected Git workflows', verified: true },
      { name: 'Automated Dependency & SAST Scanning', description: 'Continuous scanning of packages and container images for Common Vulnerabilities and Exposures (CVEs).', evidence: 'Automated CI/CD security scanning', verified: true },
      { name: 'Zero Secrets in Codebases', description: 'Secret scanning pre-commit hooks and runtime secret managers prevent API credential leakage.', evidence: 'Secret management vault', verified: true },
      { name: 'Independent Penetration Testing', description: 'Annual third-party black-box and white-box penetration testing conducted by CREST-accredited security firms.', evidence: 'Annual Pentest Executive Summary', verified: true },
      { name: 'Environment Separation', description: 'Complete physical and logical separation between Development, Staging, and Production environments with zero live student data in staging.', evidence: 'Isolated cloud VPCs', verified: true },
    ],
  },
  {
    id: 'monitoring-response',
    title: 'Monitoring & Incident Response',
    subtitle: 'Continuous Observability & Rapid Containment',
    description: 'Maintains real-time telemetry, threat detection, and structured 24/7 incident response runbooks.',
    capabilities: [
      { name: 'Centralised Security Telemetry', description: 'Real-time ingestion of application logs, edge gateway requests, and system error events for continuous anomaly monitoring.', evidence: 'Real-time telemetry stream', verified: true },
      { name: 'Automated Rate Limiting & DDoS Shield', description: 'Global edge network protects authentication and search endpoints against brute-force and volumetric DDoS attacks.', evidence: 'Edge DDoS mitigation', verified: true },
      { name: 'Documented Incident Response Plan', description: 'Tested runbooks for breach classification, containment, evidence preservation, and 72-hour regulatory notification.', evidence: 'ISMS Incident Response Plan v3', verified: true },
      { name: 'Immutable Audit Trail', description: 'Forensic record of administrative actions, user consent modifications, and moderation decisions stored in write-once audit log.', evidence: 'audit_events ledger', verified: true },
      { name: 'Post-Incident Blameless Reviews', description: 'Formal root-cause analysis (RCA) and preventive control enhancements following any platform service disruption.', evidence: 'ISMS Continual Improvement Log', verified: true },
    ],
  },
  {
    id: 'vendor-governance',
    title: 'Vendor & Subprocessor Governance',
    subtitle: 'Supply Chain Assurance & Contractual DPAs',
    description: 'Imposes rigorous security, privacy, and sovereignty standards across all third-party suppliers and LLM providers.',
    capabilities: [
      { name: 'Public Subprocessor Register', description: 'Transparent public directory listing all infrastructure, AI model providers, and operational sub-processors.', evidence: 'CareerOS Subprocessor Directory', verified: true },
      { name: 'Vendor Security Risk Assessments', description: 'Comprehensive pre-procurement security reviews, SOC 2 / ISO 27001 evaluation, and annual re-audits.', evidence: 'Vendor Risk Assessment Matrix', verified: true },
      { name: 'Data Processing Agreements (DPAs)', description: 'Binding contractual agreements incorporating Standard Contractual Clauses (SCCs) and FERPA compliance terms with all vendors.', evidence: 'Signed Subprocessor DPAs', verified: true },
      { name: 'Data Location & Sovereignty', description: 'US institutional and student data is stored and processed exclusively in US cloud regions with verified encryption.', evidence: 'US Cloud Availability Zones', verified: true },
      { name: 'Zero Training on Customer Data', description: 'Contractual zero-retention and zero-training guarantees with LLM model providers (Google Cloud Vertex AI & Anthropic Enterprise).', evidence: 'Enterprise AI Vendor Agreements', verified: true },
    ],
  },
  {
    id: 'ai-governance',
    title: 'Responsible AI & Model Governance',
    subtitle: 'Lifecycle Accountability & Anti-Bias Verification',
    description: 'Operates full-stack AI governance from pre-deployment risk mapping to continuous drift monitoring and human oversight.',
    capabilities: [
      { name: 'Public AI Use-Case & Model Registry', description: 'Detailed public disclosures of model providers, versions, training cutoffs, decision boundaries, and system owners.', evidence: 'AI Decision Governance Registry', verified: true },
      { name: 'Pre-Deployment AI Impact Assessments', description: 'Mandatory algorithmic impact assessments mapping socio-technical risks and disparate impact before new features deploy.', evidence: 'ISO/IEC 42001 AIMS Risk Reports', verified: true },
      { name: 'Independent Bias Audits (NYC LL144 & Illinois)', description: 'Annual statistical bias audits evaluating disparate impact across protected demographic categories.', evidence: 'Annual Bias Audit Publication', verified: true },
      { name: 'Meaningful Human Oversight & Appeal', description: 'Consequential matching outputs require human recruiter confirmation; users have guaranteed right of human review and appeal.', evidence: 'Human-in-the-Loop Architecture', verified: true },
      { name: 'Model Rollback & Circuit Breakers', description: 'Instant emergency rollback and heuristic fallback mechanisms if model drift, safety violations, or anomalous output rates exceed thresholds.', evidence: 'AI Routing Circuit Breakers', verified: true },
    ],
  },
];

export const COMPLIANCE_DOCUMENTS_VAULT: EvidenceDocument[] = [
  {
    id: 'doc-soc2-type2',
    frameworkId: 'soc2-type2',
    title: 'SOC 2 Type II Independent Service Auditor Report',
    documentType: 'audit_report',
    isPublic: false,
    requiresNda: true,
    version: '2025.1',
    effectiveDate: '2025-01-01',
    validUntil: '2026-02-15',
    description: 'Full independent CPA examination report covering Security, Availability, Confidentiality, Privacy, and Processing Integrity criteria.',
    fileSizeBytes: 2450000,
  },
  {
    id: 'doc-iso-27001-cert',
    frameworkId: 'iso-27001',
    title: 'ISO/IEC 27001:2022 Certificate of Registration',
    documentType: 'certificate',
    isPublic: false,
    requiresNda: true,
    version: '2024.1',
    effectiveDate: '2024-11-15',
    validUntil: '2027-11-14',
    description: 'Accredited registrar certificate confirming information security management system compliance.',
    fileSizeBytes: 420000,
  },
  {
    id: 'doc-iso-42001-cert',
    frameworkId: 'iso-42001',
    title: 'ISO/IEC 42001:2023 Artificial Intelligence Management Certificate',
    documentType: 'certificate',
    isPublic: false,
    requiresNda: true,
    version: '2025.1',
    effectiveDate: '2025-01-15',
    validUntil: '2028-01-14',
    description: 'Certificate of registration for CareerOS Artificial Intelligence Management System (AIMS).',
    fileSizeBytes: 480000,
  },
  {
    id: 'doc-dpa-standard',
    frameworkId: 'ferpa',
    title: 'CareerOS Institutional Data Processing Agreement (DPA)',
    documentType: 'dpa',
    isPublic: true,
    requiresNda: false,
    fileUrl: '/legal/dpa',
    version: 'v3.2',
    effectiveDate: '2024-09-01',
    description: 'Standard institutional DPA including FERPA terms, student privacy addendum, and standard contractual clauses.',
    fileSizeBytes: 350000,
  },
  {
    id: 'doc-subprocessors',
    frameworkId: 'iso-27701',
    title: 'CareerOS Authorized Subprocessor Register',
    documentType: 'policy',
    isPublic: true,
    requiresNda: false,
    fileUrl: '/legal/subprocessors',
    version: 'v4.0',
    effectiveDate: '2025-01-01',
    description: 'Public listing of infrastructure, database, and AI model hosting subprocessors with processing locations.',
    fileSizeBytes: 180000,
  },
  {
    id: 'doc-pentest-summary',
    frameworkId: 'nist-csf-2',
    title: 'Annual Penetration Testing Executive Summary (CREST-Accredited)',
    documentType: 'pentest_summary',
    isPublic: false,
    requiresNda: true,
    version: '2024.2',
    effectiveDate: '2024-10-15',
    validUntil: '2025-10-15',
    description: 'Executive summary report of external black-box and gray-box penetration test findings and verification of full remediation.',
    fileSizeBytes: 890000,
  },
  {
    id: 'doc-responsible-ai-policy',
    frameworkId: 'iso-42001',
    title: 'CareerOS Responsible AI Policy & Impact Assessment Methodology',
    documentType: 'policy',
    isPublic: true,
    requiresNda: false,
    fileUrl: '/trust/responsible-ai',
    version: 'v2.4',
    effectiveDate: '2025-01-15',
    description: 'Comprehensive policy detailing AI decision boundaries, risk tiers, model transparency, and human oversight.',
    fileSizeBytes: 520000,
  },
  {
    id: 'doc-accessibility-statement',
    frameworkId: 'wcag-22-aa',
    title: 'CareerOS Accessibility Conformance Statement (WCAG 2.2 AA)',
    documentType: 'policy',
    isPublic: true,
    requiresNda: false,
    fileUrl: '/trust/accessibility',
    version: '2024.1',
    effectiveDate: '2024-10-01',
    description: 'Voluntary Product Accessibility assessment and conformance declaration across web and mobile surfaces.',
    fileSizeBytes: 260000,
  },
];

export const COMPLIANCE_REGULATIONS_REGISTRY: ComplianceRegulation[] = [
  {
    id: 'nyc-ll144',
    jurisdiction: 'New York City (US)',
    regulationName: 'NYC Automated Employment Decision Tools (AEDT) Law',
    shortCode: 'NYC Local Law 144',
    applicabilityTrigger: 'Assisting employers with candidate discovery, recommendation, or qualification scoring within NYC.',
    systemsAffected: ['SYS-AEDT-002 (Talent Discovery Engine)'],
    effectiveDate: '2023-07-05',
    requiredControls: [
      'Annual independent statistical bias audit',
      'Public bias audit summary and adverse impact ratios',
      '10-business-day advance candidate notice prior to AEDT use',
      'Clear alternative selection process and human review request mechanism',
    ],
    implementationStatus: 'compliant',
    owner: 'Chief Trust & Compliance Officer',
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'CareerOS enforces recruiter human review before any candidate interview decision is finalized.',
  },
  {
    id: 'colorado-ai-sb205',
    jurisdiction: 'Colorado (US)',
    regulationName: 'Colorado Consumer Protections in Artificial Intelligence Act',
    shortCode: 'Colorado SB 24-205',
    applicabilityTrigger: 'High-risk AI systems making or acting as a substantial factor in consequential decisions (employment & education).',
    systemsAffected: ['SYS-AEDT-002 (Talent Discovery)', 'SYS-AIM-001 (AI Mentor)'],
    effectiveDate: '2026-02-01',
    requiredControls: [
      'Comprehensive AI risk management policy and governance program',
      'Annual impact assessments evaluating algorithmic discrimination risk',
      'Consumer notice prior to consequential decision deployment',
      'Adverse outcome explanation and right to correct personal information',
      'Guaranteed right to appeal and meaningful human review',
    ],
    implementationStatus: 'compliant',
    owner: 'AI Governance Lead',
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Engineered directly to satisfy revised Colorado developer and deployer accountability duties.',
  },
  {
    id: 'illinois-aiva',
    jurisdiction: 'Illinois (US)',
    regulationName: 'Artificial Intelligence Video Interview & Employment Act',
    shortCode: '820 ILCS 42/',
    applicabilityTrigger: 'Using artificial intelligence to evaluate candidate interviews or application submissions.',
    systemsAffected: ['SYS-AEDT-002 (Talent Discovery Engine)'],
    effectiveDate: '2020-01-01',
    requiredControls: [
      'Pre-analysis notice explaining AI evaluation characteristics',
      'Explicit candidate consent prior to AI assessment',
      'Confidentiality safeguards and 30-day candidate deletion rights',
      'Reporting on racial/ethnic demographic distribution of applicants',
    ],
    implementationStatus: 'compliant',
    owner: 'Chief Trust & Compliance Officer',
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'No video facial analysis is used by CareerOS. Application assessments operate under full consent.',
  },
  {
    id: 'ferpa-34cfr99',
    jurisdiction: 'United States (Federal)',
    regulationName: 'Family Educational Rights and Privacy Act',
    shortCode: '34 CFR Part 99',
    applicabilityTrigger: 'Access to student education records from secondary and postsecondary institutions.',
    systemsAffected: ['All School Workspaces & Student Accounts'],
    effectiveDate: '1974-11-19',
    requiredControls: [
      'Direct institutional control under the School Official exception',
      'Purpose-bound processing strictly for educational guidance',
      'Prohibition on re-disclosure or commercial advertising exploitation',
      'Binding institutional Data Processing Agreements with return/deletion rights',
    ],
    implementationStatus: 'compliant',
    owner: 'Legal & Compliance Counsel',
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Standardized for school and district procurement with dedicated counsel support.',
  },
  {
    id: 'coppa-16cfr312',
    jurisdiction: 'United States (Federal)',
    regulationName: "Children's Online Privacy Protection Rule",
    shortCode: '16 CFR Part 312',
    applicabilityTrigger: 'Online interaction with children under the age of 13.',
    systemsAffected: ['Registration Gating & Minor Profile Flows'],
    effectiveDate: '2000-04-21',
    requiredControls: [
      'Standard platform self-registration restricted to 13+',
      'Verifiable parental consent or school institutional authorization for under-13',
      'Direct notice to parents of data practices and deletion rights',
      'Zero sale, behavioral advertising, or unnecessary data collection',
    ],
    implementationStatus: 'aligned',
    owner: 'Chief Privacy Officer',
    lastReviewedAt: '2026-08-16T00:00:00Z',
    notes: 'Configurable age-policy controls with cryptographically signed consent audit trails.',
  },
];
