import { createClient } from '@/lib/supabase/client';
import {
  PartnerEcosystemItem,
  PublicWorkforceResource,
  PartnershipPrinciple,
  EcosystemProgressionStep,
  SpecialistPathway,
} from '@/types/partners';

export const STRATEGIC_PARTNERS_REGISTRY: PartnerEcosystemItem[] = [
  {
    id: 'nawb',
    name: 'National Association of Workforce Boards',
    slug: 'nawb',
    organizationType: 'nonprofit',
    relationshipType: 'workforce_partner',
    category: 'Workforce & Opportunity',
    positioning: "Connecting CareerOS with the people building America's workforce.",
    shortDescription: "Workforce development boards are fundamental to connecting local talent, employers, training and economic opportunity.",
    partnershipReason: "CareerOS is designed to complement the vital regional work of workforce development boards across the American Job Center ecosystem rather than attempting to replace human workforce infrastructure.",
    capabilityProvided: "Regional workforce board integration, American Job Center mapping, local employer coalition access, and public workforce investment alignment.",
    audienceSupported: ['Job Seekers', 'Adult Learners', 'Workforce Boards', 'Local Employers', 'Community Colleges'],
    websiteUrl: 'https://www.nawb.org',
    featured: true,
    sortOrder: 1,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'betterhelp',
    name: 'BetterHelp',
    slug: 'betterhelp',
    organizationType: 'enterprise',
    relationshipType: 'wellbeing_partner',
    category: 'Wellbeing & Human Support',
    positioning: 'Because careers affect people, not profiles.',
    shortDescription: 'Professional mental-health support for adult professionals navigating workplace burnout, anxiety, and career disruption.',
    partnershipReason: 'CareerOS AI mentors are strictly not therapists. When a career conversation moves beyond mentorship into clinical stress or personal distress, responsible technology requires an immediate, compassionate human clinical pathway.',
    capabilityProvided: '24/7 licensed professional tele-therapy network, private consent boundaries, confidential adult referral pathways, and specialized workplace stress support.',
    audienceSupported: ['Adult Professionals', 'Career Pivoters', 'Remote Workers', 'Displaced Workers'],
    websiteUrl: 'https://www.betterhelp.com',
    featured: true,
    sortOrder: 2,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'talkspace',
    name: 'Talkspace',
    slug: 'talkspace',
    organizationType: 'enterprise',
    relationshipType: 'wellbeing_partner',
    category: 'Wellbeing & Human Support',
    positioning: 'Specialist support for younger people when career pressure becomes something more.',
    shortDescription: 'Youth and adolescent behavioral healthcare supporting students and school districts under strict safeguarding boundaries.',
    partnershipReason: 'Talkspace complements the adult wellbeing pathway by supporting CareerOS’ youth/school ecosystem. CareerOS provides career mentorship; professional adolescent mental health remains with licensed clinical providers.',
    capabilityProvided: 'Youth-specialized licensed tele-health, school district integration capabilities, adolescent anxiety support, and crisis escalation protocols.',
    audienceSupported: ['High School Students', 'Young Adults', 'School Districts', 'Youth Programs'],
    websiteUrl: 'https://www.talkspace.com',
    featured: true,
    sortOrder: 3,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'handshake',
    name: 'Handshake',
    slug: 'handshake',
    organizationType: 'enterprise',
    relationshipType: 'employment_partner',
    category: 'Early Careers & Opportunity',
    positioning: 'Connecting emerging talent with the organizations looking for it.',
    shortDescription: 'Bridging prepared, verified student capability with active early-career hiring opportunities across universities and enterprises.',
    partnershipReason: 'CareerOS helps a person understand where they are, where they could go, and what skills they need. Employment ecosystems like Handshake connect that prepared talent with actual early-career roles.',
    capabilityProvided: 'Early-career opportunity feeds, campus recruitment alignment, university career center integration, and verified employer connections.',
    audienceSupported: ['College Students', 'Recent Graduates', 'Universities', 'Early-Career Employers'],
    websiteUrl: 'https://joinhandshake.com',
    featured: false,
    sortOrder: 4,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'coursera',
    name: 'Coursera',
    slug: 'coursera',
    organizationType: 'enterprise',
    relationshipType: 'education_partner',
    category: 'Learning & Skills',
    positioning: 'Turning a skills gap into a learning path.',
    shortDescription: 'Connecting identified capability gaps with world-class university and industry credentials to drive measurable skill progression.',
    partnershipReason: 'CareerOS does not merely diagnose skill deficiencies; it turns development needs into structured, tangible learning paths with accredited university and industry partners.',
    capabilityProvided: 'Accredited university courses, professional certificates from leading global employers, modular skill pathways, and automated completion verification.',
    audienceSupported: ['Students', 'Career Pivoters', 'Lifelong Learners', 'Upskilling Professionals'],
    websiteUrl: 'https://www.coursera.org',
    featured: true,
    sortOrder: 5,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'lightcast',
    name: 'Lightcast',
    slug: 'lightcast',
    organizationType: 'enterprise',
    relationshipType: 'data_provider',
    category: 'Workforce Intelligence',
    positioning: 'Career decisions grounded in the labor market.',
    shortDescription: 'Bringing high-fidelity labor-market analytics, regional wage intelligence, and skill demand signals into Career Twin models.',
    partnershipReason: 'Career advice should not exist in an information vacuum. Lightcast labor-market intelligence provides the empirical signals that power Career Twin occupational adjacency and compensation trajectory modeling.',
    capabilityProvided: 'Real-time employer demand telemetry, occupational task breakdown, regional wage indexes, emerging skill taxonomies, and career adjacency graphs.',
    audienceSupported: ['All CareerOS Users', 'Workforce Boards', 'Curriculum Planners', 'Enterprise Strategists'],
    websiteUrl: 'https://lightcast.io',
    featured: true,
    sortOrder: 6,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'credly',
    name: 'Credly by Pearson',
    slug: 'credly',
    organizationType: 'enterprise',
    relationshipType: 'credential_partner',
    category: 'Credentials & Evidence',
    positioning: 'Skills should be demonstrated, not merely claimed.',
    shortDescription: 'Recognizing and surfacing verifiable professional credentials and digital badges directly within the sovereign Career Passport.',
    partnershipReason: 'As CareerOS builds an evolving Career Twin for each individual, verified credentials from 30,000+ issuers provide tamper-proof evidence of capability for employers and institutions.',
    capabilityProvided: 'Open Badges standard verification, automated credential ingestion, cryptographically signed qualification proof, and employer skill validation.',
    audienceSupported: ['Certified Professionals', 'Trade Practitioners', 'Students', 'Credential Issuers'],
    websiteUrl: 'https://www.credly.com',
    featured: false,
    sortOrder: 7,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'britebound',
    name: 'Britebound',
    slug: 'britebound',
    organizationType: 'startup',
    relationshipType: 'education_partner',
    category: 'Youth & Career Readiness',
    positioning: 'Career exploration should start before somebody needs a job.',
    shortDescription: 'Empowering young people to explore interests, understand modern career possibilities, and connect school learning with future opportunities.',
    partnershipReason: 'Mission alignment around early exploration for middle and high school students, creating an engaging, non-linear bridge into CareerOS lifelong career navigation.',
    capabilityProvided: 'Youth career exploration curriculum, student interest inventories, interactive career discovery for secondary schools, and educator resources.',
    audienceSupported: ['Middle School Students', 'High School Students', 'Educators', 'Parents'],
    websiteUrl: 'https://britebound.com',
    featured: false,
    sortOrder: 8,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'hiring-our-heroes',
    name: 'Hiring Our Heroes',
    slug: 'hiring-our-heroes',
    organizationType: 'nonprofit',
    relationshipType: 'workforce_partner',
    category: 'Specialist Career Pathways',
    positioning: 'Military experience is experience.',
    shortDescription: 'Translating military occupational specialties and command experience into high-impact civilian leadership opportunities.',
    partnershipReason: 'Transitioning service members and military spouses have distinct career navigation needs. CareerOS provides sovereign capability translation tools mapping military service into civilian competencies.',
    capabilityProvided: 'Military MOS-to-civilian skill translation, Corporate Fellowship program alignment, military spouse career continuity, and veteran hiring coalitions.',
    audienceSupported: ['Veterans', 'Transitioning Service Members', 'Military Spouses', 'Defense Employers'],
    websiteUrl: 'https://www.hiringourheroes.org',
    featured: false,
    sortOrder: 9,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'united-way-211',
    name: 'United Way 211',
    slug: 'united-way-211',
    organizationType: 'nonprofit',
    relationshipType: 'community_partner',
    category: 'Whole-Person Support',
    positioning: "Sometimes the barrier to work isn't work.",
    shortDescription: 'Connecting individuals with hyper-local community services for childcare, transportation, housing, and emergency stability.',
    partnershipReason: 'Career progression is frequently blocked by practical life challenges outside a resume. CareerOS helps users discover external community resources rather than pretending AI can solve whole-person challenges in isolation.',
    capabilityProvided: 'Local social care navigation across 50 states, childcare assistance lookup, transit subsidy discovery, and housing/utility support integration.',
    audienceSupported: ['Job Seekers with Barriers', 'Low-Income Workers', 'Single Parents', 'Community Advocates'],
    websiteUrl: 'https://www.211.org',
    featured: false,
    sortOrder: 10,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
  {
    id: 'jff',
    name: 'Jobs for the Future (JFF)',
    slug: 'jff',
    organizationType: 'nonprofit',
    relationshipType: 'strategic_partner',
    category: 'Workforce Innovation',
    positioning: 'Building better pathways between learning and work.',
    shortDescription: 'Advancing skills-first employment, work-based learning, and national policy innovation for economic mobility.',
    partnershipReason: 'CareerOS collaborates with national workforce innovation leaders to ensure registered apprenticeships, community colleges, and non-degree pathways receive full parity in career development.',
    capabilityProvided: 'Workforce policy research, skills-based hiring frameworks, apprenticeship acceleration, and regional economic mobility initiatives.',
    audienceSupported: ['Policy Makers', 'Workforce Innovators', 'Apprenticeship Sponsors', 'Underrepresented Workers'],
    websiteUrl: 'https://www.jff.org',
    featured: false,
    sortOrder: 11,
    relationshipStatus: 'discussion',
    publicDisplayApproved: false,
    logoUseApproved: false,
    attributionRequired: false,
    active: true,
    createdAt: '2026-08-18T00:00:00Z',
    updatedAt: '2026-08-18T00:00:00Z',
  },
];

export const PUBLIC_WORKFORCE_RESOURCES: PublicWorkforceResource[] = [
  {
    id: 'careeronestop',
    name: 'CareerOneStop',
    slug: 'careeronestop',
    dataCategory: 'Careers, Training & Employment',
    purpose: ['Job Search', 'Career Exploration', 'Training & Education', 'Workforce Resources', 'Licensing Databases'],
    description: 'The flagship U.S. Department of Labor portal providing authoritative career descriptions, state occupational licensing directories, and local American Job Center locations.',
    shortDescription: 'Federal career exploration, training lookup, and American Job Center location services.',
    howCareerOSUsesIt: 'Populates occupational profiles, training program discovery, and American Job Center mapping used in CareerOS career exploration and opportunity search features.',
    officialSponsor: 'U.S. Department of Labor, Employment and Training Administration (USDOL/ETA)',
    websiteUrl: 'https://www.careeronestop.org',
    url: 'https://www.careeronestop.org',
    attributionText: 'CareerOneStop is sponsored by the U.S. Department of Labor, Employment and Training Administration. Reference to CareerOneStop does not imply endorsement by the U.S. Department of Labor.',
    isFederalResource: true,
  },
  {
    id: 'onet',
    name: 'O*NET® (Occupational Information Network)',
    slug: 'onet',
    dataCategory: 'Occupations & Skills',
    purpose: ['Occupational Taxonomies (SOC)', 'Skills & Task Breakdown', 'Knowledge & Abilities', 'Work Activities', 'Worker Characteristics'],
    description: "The nation's primary source of occupational information, providing standardized taxonomies that define thousands of occupations, required capabilities, and work context.",
    shortDescription: 'Authoritative US federal occupational taxonomy — the foundation of standardized skill and career classification.',
    howCareerOSUsesIt: 'Provides the Standard Occupational Classification (SOC) taxonomy, skills framework, and knowledge structures that underpin Career Twin capability mapping and career exploration.',
    officialSponsor: 'U.S. Department of Labor / Employment and Training Administration (USDOL/ETA)',
    websiteUrl: 'https://www.onetonline.org',
    url: 'https://www.onetonline.org',
    attributionText: 'O*NET® is a trademark of the U.S. Department of Labor, Employment and Training Administration (USDOL/ETA). CareerOS uses O*NET information under open database terms; this does not constitute an endorsement by USDOL.',
    trademarkNotice: 'O*NET® is a registered trademark of the USDOL/ETA.',
    isFederalResource: true,
  },
  {
    id: 'apprenticeship-gov',
    name: 'Apprenticeship.gov',
    slug: 'apprenticeship-gov',
    dataCategory: 'Registered Apprenticeships',
    purpose: ['Registered Apprenticeships', 'Work-Based Learning', 'Employer Sponsors', 'Educator Pathways', 'State Apprenticeship Agencies'],
    description: 'The official federal platform for Registered Apprenticeships, connecting job seekers, employers, and educators with accredited earn-and-learn career pathways.',
    shortDescription: 'Official federal Registered Apprenticeship database with employer sponsors, pathways, and state apprenticeship agencies.',
    howCareerOSUsesIt: 'Surfaces Registered Apprenticeship opportunities in pathway recommendations, particularly for trades, technical, and work-based learning career routes.',
    officialSponsor: 'U.S. Department of Labor, Office of Apprenticeship',
    websiteUrl: 'https://www.apprenticeship.gov',
    url: 'https://www.apprenticeship.gov',
    attributionText: 'Apprenticeship.gov is operated by the U.S. Department of Labor. Reference to Apprenticeship.gov does not imply federal agency endorsement.',
    isFederalResource: true,
  },
];


export const ECOSYSTEM_PROGRESSION_STEPS: EcosystemProgressionStep[] = [
  {
    stepNumber: 1,
    stage: 'ANALYSIS',
    title: 'Career Twin Identifies Capability Gap',
    entityName: 'CareerOS AI Core',
    entityRole: 'Diagnostic & Pathfinding',
    description: 'Continuous analysis of market requirements identifies an actionable skill deficiency blocking transition into target senior roles.',
    dataOutput: 'Skill Gap: Distributed Systems Architecture (Level 3)',
  },
  {
    stepNumber: 2,
    stage: 'LEARN',
    title: 'Curated University Learning Path',
    entityName: 'Coursera',
    entityRole: 'Education Provider',
    description: 'CareerOS generates a structured learning module with an accredited university or industry partner, focusing exclusively on the missing competency.',
    dataOutput: 'Enrollment: Cloud Systems Specialization',
  },
  {
    stepNumber: 3,
    stage: 'VERIFY',
    title: 'Tamper-Proof Credential Issued',
    entityName: 'Credly by Pearson',
    entityRole: 'Credential Network',
    description: 'Upon successful completion, an accredited digital badge is cryptographically anchored to the user’s sovereign Career Passport.',
    dataOutput: 'Verified Open Badge: AWS Cloud Systems Architect',
  },
  {
    stepNumber: 4,
    stage: 'UPDATE',
    title: 'Career Twin Model Compounding',
    entityName: 'CareerOS Passport',
    entityRole: 'Sovereign Data Asset',
    description: 'The newly verified capability updates the user’s multi-dimensional Career Twin, expanding their qualified career horizons.',
    dataOutput: 'Profile Verified Score: +14% Capability Increase',
  },
  {
    stepNumber: 5,
    stage: 'SIGNALS',
    title: 'Real-Time Labor Market Signals',
    entityName: 'Lightcast',
    entityRole: 'Workforce Intelligence',
    description: 'Regional demand metrics validate emerging salary premiums and surging employer requirements for the newly acquired skill set.',
    dataOutput: 'Demand Index: +28% Regional Growth | $128k Median',
  },
  {
    stepNumber: 6,
    stage: 'MATCH',
    title: 'High-Fit Opportunity Matching',
    entityName: 'CareerOS Graph',
    entityRole: 'Opportunity Engine',
    description: 'Algorithm matches the upgraded Career Twin against high-integrity opportunities with zero demographic or pedigree bias.',
    dataOutput: 'Matched: 12 High-Confidence Career Openings',
  },
  {
    stepNumber: 7,
    stage: 'CONNECT',
    title: 'Direct Network & Employer Connection',
    entityName: 'Handshake / Workforce Network',
    entityRole: 'Hiring & Workforce Ecosystem',
    description: 'User seamlessly connects with hiring teams, registered apprenticeship sponsors, or regional workforce boards with verified proof.',
    dataOutput: 'Application Transmitted with Cryptographic Proof',
  },
];

export const PARTNERSHIP_PRINCIPLES: PartnershipPrinciple[] = [
  {
    id: 'useful',
    number: '01',
    title: 'Useful to the Individual',
    statement: 'Every partnership must deliver a tangible, compounding benefit for the person.',
    description: 'We do not form commercial alliances for vanity or logo collection. Every relationship must solve an authentic career development, learning, or wellbeing need.',
  },
  {
    id: 'trusted',
    number: '02',
    title: 'Trusted in Their Field',
    statement: 'Partners must bring deep expertise CareerOS should not pretend to possess.',
    description: 'From licensed adolescent tele-health to accredited university credentials, we collaborate with domain specialists rather than building superficial in-house substitutes.',
  },
  {
    id: 'responsible',
    number: '03',
    title: 'Responsible with Personal Data',
    statement: 'Partnership never means unrestricted access to individual data.',
    description: 'All data exchanges require explicit user consent, strict purpose limitation, and contractual Data Processing Agreements. Zero personal data is ever sold.',
  },
  {
    id: 'human',
    number: '04',
    title: 'Human Where Humans Matter',
    statement: 'Technology must recognize its ethical and clinical boundaries.',
    description: 'CareerOS AI mentors provide career navigation. When an individual encounters clinical stress or life barriers, we gracefully route to qualified human professionals.',
  },
  {
    id: 'integrity',
    number: '05',
    title: 'Opportunity Over Advertising',
    statement: 'Commercial relationships must never silently bias career guidance.',
    description: 'Career recommendations are driven by objective fit, empirical labor-market signals, and user choice. We maintain absolute transparency over all sponsored placements.',
  },
];

export const SPECIALIST_PATHWAYS: SpecialistPathway[] = [
  {
    id: 'students',
    audience: 'High School & Secondary Learners',
    subtitle: 'Exploratory & Readiness',
    partnerName: 'Britebound / Education Ecosystem',
    category: 'Youth & Career Readiness',
    challenge: 'Early career discovery terminates upon high school graduation, leaving young people without a continuous lifelong career record.',
    solution: 'Persistent, minor-safeguarded career exploration bridging high school interests with registered apprenticeships and post-secondary pathways.',
    keyCapabilities: ['Interest Inventories', 'Parental Consent Framework', 'Educator Dashboard', 'Apprenticeship Discovery'],
  },
  {
    id: 'early-careers',
    audience: 'University Students & Graduates',
    subtitle: 'Campus to Enterprise Transition',
    partnerName: 'Handshake / Early Talent Network',
    category: 'Early Careers & Opportunity',
    challenge: 'Graduates struggle to bridge academic qualifications with verified employer capability requirements.',
    solution: 'Direct translation of course competencies into verifiable digital portfolios matched against active early-career hiring pipelines.',
    keyCapabilities: ['University Portfolio Ingestion', 'Early Career Job Feeds', 'Campus Recruiter Alignment', 'Verified Coursework'],
  },
  {
    id: 'workforce-transition',
    audience: 'Adult Workers & Pivoters',
    subtitle: 'Regional Reskilling & Mobility',
    partnerName: 'NAWB / Workforce Development Boards',
    category: 'Workforce & Opportunity',
    challenge: 'Displaced workers face fragmented state training resources and opaque local hiring networks.',
    solution: 'Deep integration with the 550+ American Job Center network, providing guided reskilling into high-demand regional occupations.',
    keyCapabilities: ['American Job Center Finder', 'WIOA Program Mapping', 'Regional Wage Indexes', 'Living-Wage Career Ladders'],
  },
  {
    id: 'veterans',
    audience: 'Veterans & Military Families',
    subtitle: 'Service to Civilian Transition',
    partnerName: 'Hiring Our Heroes',
    category: 'Specialist Career Pathways',
    challenge: 'Military command and technical experience is often lost in translation on traditional civilian resumes.',
    solution: 'Algorithmic MOS-to-Civilian translation taxonomy proving operational leadership to private-sector hiring coalitions.',
    keyCapabilities: ['MOS Code Translation', 'Corporate Fellowship Matching', 'Spouse Career Portability', 'Security Clearance Mapping'],
  },
  {
    id: 'upskilling',
    audience: 'Practicing Professionals',
    subtitle: 'Continuous Skill Compounding',
    partnerName: 'Coursera & Credly by Pearson',
    category: 'Learning & Credentials',
    challenge: 'Online course certificates remain isolated in email receipts without compounding into real promotion opportunities.',
    solution: 'Automated skill gap identification connected directly with accredited micro-credentials and cryptographic passport proof.',
    keyCapabilities: ['Skill Deficit Diagnostic', 'University Certifications', 'Open Badges 3.0', 'Competency Compounding'],
  },
  {
    id: 'social-barriers',
    audience: 'Individuals Facing Life Barriers',
    subtitle: 'Whole-Person Support',
    partnerName: 'United Way 211 / Social Care',
    category: 'Whole-Person Support',
    challenge: 'Non-work obstacles (childcare, transit, housing, food insecurity) frequently derail career retention.',
    solution: 'Seamless navigation to hyper-local social care and essential community assistance programs alongside career mentoring.',
    keyCapabilities: ['Childcare Subsidy Locator', 'Transit Assistance', 'Emergency Housing Directory', 'Confidential Local Referrals'],
  },
];

/**
 * Returns the ecosystem partners.
 * In production: strictly returns records with active=true AND publicDisplayApproved=true.
 * In development/staging/preview: returns the intended future-state strategic partners.
 */
export async function getEcosystemPartners(options?: {
  preview?: boolean;
}): Promise<PartnerEcosystemItem[]> {
  const isPreview = options?.preview ?? (process.env.NODE_ENV !== 'production');

  try {
    const supabase = createClient();
    let query = supabase
      .from('partners')
      .select('*')
      .eq('active', true)
      .order('sort_order', { ascending: true });

    if (!isPreview) {
      query = query.eq('public_display_approved', true);
    }

    const { data, error } = await query;

    if (!error && data && data.length > 0) {
      return data.map((d: any) => ({
        id: d.slug || d.id,
        name: d.name,
        slug: d.slug,
        organizationType: d.organization_type || 'enterprise',
        relationshipType: d.relationship_type || 'strategic_partner',
        category: (d.category || d.primary_category || 'Workforce & Opportunity') as any,
        positioning: d.short_description || d.description || '',
        shortDescription: d.short_description || d.description || '',
        partnershipReason: d.partnership_reason || d.strategic_rationale || '',
        capabilityProvided: d.capability_provided || '',
        audienceSupported: d.audience_supported || d.target_audiences || [],
        websiteUrl: d.website_url || '',
        logoUrl: d.logo_url,
        logoDarkUrl: d.logo_dark_url,
        featured: d.featured || false,
        sortOrder: d.sort_order || 100,
        relationshipStatus: d.relationship_status || 'discussion',
        publicDisplayApproved: d.public_display_approved || false,
        logoUseApproved: d.logo_use_approved || false,
        attributionRequired: d.attribution_required || false,
        attributionCopy: d.attribution_copy,
        legalNotes: d.legal_notes,
        active: d.active ?? true,
        createdAt: d.created_at,
        updatedAt: d.updated_at,
        lastVerifiedAt: d.last_verified_at,
      }));
    }
  } catch (err) {
    // Fallback to static registry in case of offline / test environment
  }

  if (isPreview) {
    return STRATEGIC_PARTNERS_REGISTRY;
  }

  return STRATEGIC_PARTNERS_REGISTRY.filter((p) => p.publicDisplayApproved);
}
